### ISSUE TITLE
Add validator for naming of Modules

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#115]
**The Issue**
We need to add a validator that makes you adhere to the k8s naming convention when you are defining your Module name.

**Comment by petar-cvit** [comment]
The validation needs to be added to the rules on module name [here](https://github.com/cyclops-ui/cyclops/blob/6a4cc6587c561b456547340a989b9cc301bd6a9f/cyclops-ui/src/components/pages/new_module.tsx#L917).

You can find more about antd and form [here](https://ant.design/components/form)
