### ISSUE TITLE
Support changing module template versions

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#152]
**Is your feature request related to a problem? Please describe.**
Once you create a Module, you will likely want to upgrade that template over time. Add support for changing template versions on existing Modules

**Comment by Sheikh-Abubaker** [comment]
Hey there @petar-cvit I think this feature is already implemented ?

**Comment by petar-cvit** [comment]
Exactly, thanks for bringing this up! Closing

**Comment by Sheikh-Abubaker** [comment]
> Exactly, thanks for bringing this up! Closing

You're welcome 😅
