### ISSUE TITLE
Get logs for Deployments and Statefulsets

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#157]
**Is your feature request related to a problem? Please describe.**
Currently, you can check logs only for specific pods, but you should be able to see it on logs higher level resources like Deployments, Statefulsets...

**Describe the solution you'd like**
Add a button on the Deployment/Statfulset/... view

**Comment by hanshal101** [comment]
I can work on this.

**Comment by hanshal101** [comment]
I researched about this, looked on `client-go` and some blogs but didn't found any specific logs for `Deployments`. All of them had  logs for the pod in the deployment. According to me the `Deployment Logs` should be the collection of logs of all pods present in the deployment. 
What do you think about this?

**Comment by petar-cvit** [comment]
Of course @hanshal101!
I tried researching if there is some smooth way to just fetch it from the API, but I think you will need to fetch all of the pods for that Deployment/Statefulset and aggregate their logs

**Comment by hanshal101** [comment]
Ok then will do this
