### ISSUE TITLE
Create Cyclops CLI to be able to update modules in terminal/CI

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#176]
**Is your feature request related to a problem? Please describe.**
Create a cli that can be used to CRUD modules. It would be useful in CI and for some bulk actions.

Make it easy to install and with simple actions

**Comment by hanshal101** [comment]
Hey @petar-cvit do you want to build the complete CLI?
If yes then I have some experience in building this.

**Comment by petar-cvit** [comment]
Hey @hanshal101, of course, give it a go!

The best thing would be to call the API on the Cyclops controller and not do any of the logic in the cli itself and make it as lightweight as possible.

Can you implement only get functions for the start, and then we can open new issues for other functionalities? If that's okay with you, I will update the issue description.

**Comment by hanshal101** [comment]
Yup this sounds good to me. I'll do the get functions. Also please specify the commands we need and their description.

**Comment by petar-cvit** [comment]
Opened a project for the CLI efforts
