### ISSUE TITLE
Initialize Cyclops CLI

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#191]
Initialize Cyclops CLI in the https://github.com/cyclops-ui/cyclops repo as separate folder.

I would love to call it `cyctl`, but would love to hear other ideas

Definiton of done:
- initialized `/cyctl` folder as a Go project
- `cyctl` can be compiled
- there is a `cyctl help` that will print out what cyctl and gives a short overview of the CLI

**Comment by hanshal101** [comment]
Let me work on this.

**Comment by petar-cvit** [comment]
Great, feel free to take it! You can post any updates/concerns here
