### ISSUE TITLE
Add Cyclops CLI to Homebrew

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#192]
Setup the installation of Cyclops CLI and make it available using [Homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew)

**Comment by SpiffyEight77** [comment]
@petar-cvit 
Sorry to bother you at this moment. 🙇🏻‍♂️

It seems that this task hasn't started yet.

I have experience with creating homebrew formulas and am interested in this task. 

Would you mind assigning it to me?

**Comment by petar-cvit** [comment]
Hey @SpiffyEight77, sure thing. Could you list the steps you will take to add cyctl to brew? I never added anything there so I'm curious if we need to add anything to our repo as well

**Comment by SpiffyEight77** [comment]
@petar-cvit 
Thank you for your quick response.

- I will build multiple architectures for the binary locally.
- Check if adding a makefile could simplify the build process.
  -  Release the new version of Cyclops.
- Create the cyctl.rb file to facilitate building the Homebrew formula.

```
class Porter < Formula
  desc "customizable UI for Kubernetes workloads "
  homepage "https://cyclops-ui.com/"
  url "https://github.com/cyclops-ui/cyclops.git",
    tag:      "v0.5.0",
    revision: "3a5ad6428f51a9f506c7b1d62bee482789e91ad8"
  license "Apache-2.0"
  head "https://github.com/cyclops-ui/cyclops.git", branch: "main"

  depends_on "go" => :build
  depends_on "make" => :build

  def install
    system "make", "build"

    bin.install "bin/cyctl"

    generate_completions_from_executable(bin/"cyctl", "completion")
  end

  test do
    assert_match "Cyclops gives you a UI containing fields you define yourself to manage your K8s workloads.",
                  shell_output("#{bin}/cyctl -h")
  end
end
```

**Comment by SpiffyEight77** [comment]
@petar-cvit 
Thank you for your quick response.

- I will build multiple architectures for the binary locally.
- Check if adding a makefile could simplify the build process.
  -  Release the new version of Cyclops.
- Create the cyctl.rb file to facilitate building the Homebrew formula.

```
class Cyctl < Formula
  desc "customizable UI for Kubernetes workloads "
  homepage "https://cyclops-ui.com/"
  url "https://github.com/cyclops-ui/cyclops.git",
    tag:      "v0.5.0",
    revision: "3a5ad6428f51a9f506c7b1d62bee482789e91ad8"
  license "Apache-2.0"
  head "https://github.com/cyclops-ui/cyclops.git", branch: "main"

  depends_on "go" => :build
  depends_on "make" => :build

  def install
    system "make", "build"

    bin.install "bin/cyctl"

    generate_completions_from_executable(bin/"cyctl", "completion")
  end

  test do
    assert_match "Cyclops gives you a UI containing fields you define yourself to manage your K8s workloads.",
                  shell_output("#{bin}/cyctl -h")
  end
end
```

**Comment by petar-cvit** [comment]
Can we make a GH action or add goreleaser to our repo to build new versions automatically? It would be great if you could set that up too

**Comment by SpiffyEight77** [comment]
Of course, I would be happy to do these tasks. 🙇🏻‍♂️

**Comment by petar-cvit** [comment]
Great! Assigning this to you. Let us know if you need any guidance

**Comment by SpiffyEight77** [comment]
Thank you so much.🙇🏻‍♂️

**Comment by SpiffyEight77** [comment]
@petar-cvit 
Thank you for your message. I'm a bit confused about a small issue. 

How do we determine the version of cyctl? 
It seems that hardcoding for it now, if I use GHA to release the new version, for example should I release as 0.2.x dynamically?

**Comment by petar-cvit** [comment]
The plan is it to build and release a new version of `cyctl` on each new release/tag on the GH repo. So the current version of cyctl would be `v0.5.0`

We would remove the v0.2.0 from the code of course

**Comment by SpiffyEight77** [comment]
@petar-cvit 
Thank you for your quick response to clear up my confusion.
I will submit the PR as soon as possible this weekend. 🙇🏻‍♂️

**Comment by petar-cvit** [comment]
Thanks @SpiffyEight77, let me know if you will have any questions or if there is something we can help with

**Comment by SpiffyEight77** [comment]
Hey @petar-cvit, sorry to bother you. 
I've submitted a [PR](https://github.com/Homebrew/homebrew-core/pull/173870) to homebrew-core for cyctl based on the release of v0.6.2. 
Could you please take a look at this PR when you're available?

**Comment by petar-cvit** [comment]
@SpiffyEight77  Thanks! I checked the PR, and you left porter on line 7 😄

**Comment by SpiffyEight77** [comment]
@petar-cvit
Thanks a lot, minor issue resolved.👍🏻

**Comment by SpiffyEight77** [comment]
@petar-cvit 
The [PR](https://github.com/Homebrew/homebrew-core/pull/173870) for `homebrew-core` has been merged.

To ensure the latest version is set for `cyctl`, please retain the `CliVersion` definition in the `common` package.

I think this issue can be closed.

**Comment by petar-cvit** [comment]
> To ensure the latest version is set for cyctl, please retain the CliVersion definition in the common package.

@SpiffyEight77 

So we just have to make sure that this variable exists in the common package but don't have to change it, right?

**Comment by SpiffyEight77** [comment]
> So we just have to make sure that this variable exists in the common package but don't have to change it, right?

**Comment by petar-cvit** [comment]
@SpiffyEight77 Nice! Awesome work on this! Thanks a lot for the contribution 🧡
