### ISSUE TITLE
Remove Redis connection

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#195]
**Describe the bug**
Previously, Cyclops depended on a Redis storage layer, but it was deprecated. There is still code for connecting to Redis, and it produces a log saying it can't connect to the instance.

That code must be removed to keep the codebase cleaner and not produce misleading logs. This log would pop up on each Cyclops start.

[Here](https://github.com/cyclops-ui/cyclops/blob/e34cfdff30e3989e3a1ac3e7788d6d119eb63fdd/cyclops-ctrl/cmd/main/main.go#L69) is the line that calls the initialization of the Redis client.

It is used for `templatesStorage,` which can also be deprecated and deleted

**Comment by hanshal101** [comment]
Hey @petar-cvit Can I have a look to this issue?

**Comment by hanshal101** [comment]
Here I think we should remove the `templatesStorage` in all the necessary areas

**Comment by petar-cvit** [comment]
exactly, if you remove it alongside the Redis client initialization, we can close the issue
