### ISSUE TITLE
Implement Cyclops CLI get methods

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#196]
Implement `get` and `list` methods for modules

list - `cyctl get modules`
list output should look similarly to kubectl get
```bash
cyctl get modules

NAME     AGE
first    61s
second   46s
```

get - `cyctl get modules my-module`
get should return the requested module as YAML fetched from the cluster

You will also need to connect to the cluster and call the K8s API directly using .kubeconfig env variable

**Comment by hanshal101** [comment]
lets add more commands
