### ISSUE TITLE
Add status description for pods

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#197]
**Is your feature request related to a problem? Please describe.**
If a pod is not started successfully, there should be a more detailed description in the UI about why it didn't start

**Comment by SpiffyEight77** [comment]
@petar-cvit
Apologies for the interruption. 
I am interested in thoroughly exploring Cyclops' source code and would like to give it a try. 
Could you please assign this task to me?

**Comment by petar-cvit** [comment]
Hey @SpiffyEight77, sure!

**Comment by SpiffyEight77** [comment]
Hey @petar-cvit, sorry for the delay—I caught COVID-19 this week. 
I'll start working on this issue next week. 🙇🏻‍♂️

**Comment by petar-cvit** [comment]
Hey @SpiffyEight77, no worries 😄

**Comment by SpiffyEight77** [comment]
Hey @petar-cvit, sorry to bother you. I'm currently working on this issue and have a question. If a pod fails to start successfully, will the latest event for this pod be displayed in some column on this page? And if other pods start successfully, will it show nothing?

<img width="1906" alt="Screenshot 2024-07-13 at 1 15 46" src="https://github.com/user-attachments/assets/c2b7eaf3-b673-4cf7-977f-c2a13448f2f6">

**Comment by SpiffyEight77** [comment]
@petar-cvit Thank you for your reply.

> Can we add the pod status description [PodTable](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/common/PodTable.tsx) which will then be showed when you open a deployment like on the picture below

I will attempt to implement this feature (pod status description) in PodTable. 🙇🏻‍♂️
