### ISSUE TITLE
On the View Manifest Modal on Rollback page, OK button lacks functionality

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#200]
### Describe the bug
When viewing the manifest, the modal displays two buttons: `Cancel` and `OK`. The `Cancel` button closes the modal, but the `OK` button lacks functionality. The `Cancel` button should be removed, and its functionality needs to be moved to the `OK` button.

### To Reproduce
1) Deploy a module through Cyclops
2) Open up the detailed overview of the module
3) Edit the configuration; change something (like the number of replicas) just so this module has a history
4) Click on the Rollback button
5) Click on the Manifest button

### Related issue
We had a similar [issue](https://github.com/cyclops-ui/cyclops/issues/126) with the View Manifest Modal.

**Comment by Wasiim105** [comment]
I would like to take this issue. Can you please tell me which part of the code should into

**Comment by hanshal101** [comment]
Hey @Wasiim105 you have to make changes to this `file`.  [LINK](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/History.tsx). Here when the user clicks the Manifest in the the module's history there are 2 buttons shown. The `OK` and the `CANCEL`. Here we need to make sure that you remove the `CANCEL` button and make the `OK` button function work as the `CANCEL` button.
Hope this clears your doubt.

**Comment by KaradzaJuraj** [comment]
Hey @Wasiim105, you can take this! I will assign this issue to you.
You can do as Hanshal suggested above, thanks @hanshal101 🫶 
Also, you can check out the PR related to a similar [issue](https://github.com/cyclops-ui/cyclops/issues/126).

**Comment by Wasiim105** [comment]
![Screenshot (17)](https://github.com/cyclops-ui/cyclops/assets/99980623/2af334b6-bc24-49e6-b5c2-a1b578c34c3f)

@hanshal101 I am unable to find the cancel button in History.tsx , there is only an OK button. I have also shared the attachment where only OK button is displaying, could you please help me out ? if I am missing out on something.

**Comment by petar-cvit** [comment]
Hey @Wasiim105, the button is on the rollback page. You can hit the `Rollback button`:
<img width="512" alt="Screenshot 2024-05-21 at 20 38 18" src="https://github.com/cyclops-ui/cyclops/assets/72022639/2376f350-a1ea-478f-bef7-b9300a06a2f7">
There, you will find a screen with the history of changes on a particular Module. Here, you can hit the `Manifest` button that will open a popup with two buttons on the bottom.
<img width="1505" alt="Screenshot 2024-05-21 at 20 40 24" src="https://github.com/cyclops-ui/cyclops/assets/72022639/2c9de897-b585-46bc-b702-d7602501250b">

The ok button doesn't do anything and the cancel just closes it. You will need to fix those two. You can find the Modal object [here](https://github.com/cyclops-ui/cyclops/blob/09c8bc64ac8bc055ad8ac9d9758eb9901ebbb5b4/cyclops-ui/src/components/pages/History.tsx#L225).

**Comment by Wasiim105** [comment]
![cyclops](https://github.com/cyclops-ui/cyclops/assets/99980623/aaeb49ba-bf55-49b3-80bd-65646432b080)


hey @hanshal101 I followed what you have said but in Rollback page I haven't find any data, It shows me "No Data".

**Comment by petar-cvit** [comment]
@Wasiim105  `Rollback` will show you how many times you changed a module. You can try editing a Module a couple of times and you should see entries on this screen

**Comment by petar-cvit** [comment]
Hey @Wasiim105, did you manage to get any data on the history screen? Let us know if we can help you

**Comment by Wasiim105** [comment]
@petar-cvit Thankyou for asking, I get the data and I am working on it.
