### ISSUE TITLE
Support for `_helpers.tpl` files

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#202]
Helm charts can have files such as `_helpers.tpl`. These files define resources commonly used among multiple YAMLs. To see an example of this file, you can use the command `helm create <name_of_your_new_chart>`, and in the templates subfolder, you should find a `_helpers.tpl` file.

With Cyclops, it seems that _`helpers.tpl` files are not working properly → the labels are generated but not the values 
`app.kubernetes.io/name: {{ include "name_of_your_new_chart.name" . }}` will equal `app.kubernetes.io/name:` (empty)

**Comment by Sheikh-Abubaker** [comment]
@KaradzaJuraj I would like to task this issue.

**Comment by KaradzaJuraj** [comment]
Awesome, feel free to post updates and questions here.

**Comment by Sheikh-Abubaker** [comment]
> With Cyclops, it seems that _`helpers.tpl` files are not working properly → the labels are generated but not the values `app.kubernetes.io/name: {{ include "name_of_your_new_chart.name" . }}` will equal `app.kubernetes.io/name:` (empty)

@KaradzaJuraj  I have a question, do you want to include a `_helpers.tpl` under templates directory for the cyclops chart ?

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, the issue is about supporting `.tpl` files while rendering a template into YAML ([here](https://github.com/cyclops-ui/cyclops/blob/52d3256dc1fe421be637acd940b4c3b5024a7779/cyclops-ctrl/internal/template/render.go#L46))

**Comment by petar-cvit** [comment]
I am doing some refactoring which will fix this issue as well
