### ISSUE TITLE
Ignore `Notes.txt` in Helm charts

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#203]
**Describe the bug**
Helm charts can hold `Notes.txt` in their `templates` subfolder. If present, this file will break Cyclops, and the module won't be deployed.

**To Reproduce**
1. Add `Notes.txt` in the `templates` subfolder of your Helm chart 
2. Open Cyclops
3. Click on the Add New Module button and load your Helm chart
4. Try to deploy it and fail :/

**This error message might be related to the issue:**
`error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}    `

**Expected behavior**
We want Cyclops to ignore this file when deploying modules.

**Comment by Sheikh-Abubaker** [comment]
@KaradzaJuraj I would like to take this issue.

**Comment by KaradzaJuraj** [comment]
@Sheikh-Abubaker Great! Feel free to post updates and questions here

**Comment by Sheikh-Abubaker** [comment]
@KaradzaJuraj Please checkout #221

**Comment by KaradzaJuraj** [comment]
Your PR does not solve this issue; Petar explained more in the review.

I suggest you look into `cyclops-ctrl/internal/template/helm.go`. The issue is in the `mapHelmChart` function when it wants to map the "templates" section.

I believe the condition should be expanded with something like `&& parts[2] != "Notes.txt"`

**Comment by Sheikh-Abubaker** [comment]
> I believe the condition should be expanded with something like `&& parts[2] != "Notes.txt"`

There was some misunderstanding I'll take a look again.

**Comment by Sheikh-Abubaker** [comment]
> I suggest you look into `cyclops-ctrl/internal/template/helm.go`. The issue is in the `mapHelmChart` function when it wants to map the "templates" section.
> 
> I believe the condition should be expanded with something like `&& parts[2] != "Notes.txt"`

@petar-cvit I modified the code with the above instructions from @KaradzaJuraj and then tried building it by referring to [CONTRIBUTING.md](https://github.com/cyclops-ui/cyclops/blob/main/CONTRIBUTING.md) but as I ran `make start`, It was then stuck at the same logs for a while then I had to `Ctrl+C` to exit.

## Here are the logs from my machine:
```
$ make start
go run -tags musl ./cmd/main
2024-04-22T14:45:37+05:30       INFO    setup   starting handler
2024-04-22T14:45:37+05:30       INFO    setup   telemetry disabled

unable to connect to redis
error bootstrapping redis dial tcp 127.0.0.1:6379: connect: connection refused
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> github.com/cyclops-ui/cycops-ctrl/internal/handler.(*Handler).pong.func1 (1 handlers)
[GIN-debug] POST   /create-config            --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).StoreConfiguration-fm (1 handlers)
[GIN-debug] GET    /create-config/:name      --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).GetConfiguration-fm (1 handlers)
[GIN-debug] GET    /configuration-details    --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).GetConfigurationsDetails-fm (1 handlers)
[GIN-debug] GET    /configuration/:name/versions --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).GetConfigurationsVersions-fm (1 handlers)       
[GIN-debug] GET    /templates                --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).GetTemplate-fm (1 handlers)
[GIN-debug] GET    /templates/initial        --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).GetTemplateInitialValues-fm (1 handlers)
[GIN-debug] GET    /templates/store          --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).ListTemplatesStore-fm (1 handlers)
[GIN-debug] PUT    /templates/store          --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).CreateTemplatesStore-fm (1 handlers)
[GIN-debug] POST   /templates/store/:name    --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).EditTemplatesStore-fm (1 handlers)
[GIN-debug] DELETE /templates/store/:name    --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Templates).DeleteTemplatesStore-fm (1 handlers)
[GIN-debug] GET    /modules/:name            --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).GetModule-fm (1 handlers)
[GIN-debug] GET    /modules/list             --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).ListModules-fm (1 handlers)
[GIN-debug] DELETE /modules/:name            --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).DeleteModule-fm (1 handlers)
[GIN-debug] POST   /modules/new              --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).CreateModule-fm (1 handlers)
[GIN-debug] POST   /modules/update           --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).UpdateModule-fm (1 handlers)
[GIN-debug] GET    /modules/:name/history    --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).GetModuleHistory-fm (1 handlers)
[GIN-debug] POST   /modules/:name/manifest   --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).Manifest-fm (1 handlers)
[GIN-debug] GET    /modules/:name/currentManifest --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).CurrentManifest-fm (1 handlers)
[GIN-debug] GET    /modules/:name/resources  --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).ResourcesForModule-fm (1 handlers)
[GIN-debug] DELETE /modules/:name/resources  --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).DeleteModuleResource-fm (1 handlers)
[GIN-debug] GET    /modules/:name/template   --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).Template-fm (1 handlers)
[GIN-debug] GET    /modules/:name/helm-template --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).HelmTemplate-fm (1 handlers)
[GIN-debug] GET    /resources/pods/:namespace/:name/:container/logs --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).GetLogs-fm (1 handlers)        
[GIN-debug] GET    /resources/pods/:namespace/:name/:container/logs/download --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).DownloadLogs-fm (1 handlers)
[GIN-debug] GET    /manifest                 --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).GetManifest-fm (1 handlers)
[GIN-debug] GET    /resources                --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Modules).GetResource-fm (1 handlers)
[GIN-debug] GET    /nodes                    --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Cluster).ListNodes-fm (1 handlers)
[GIN-debug] GET    /nodes/:name              --> github.com/cyclops-ui/cycops-ctrl/internal/controller.(*Cluster).GetNode-fm (1 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Environment variable PORT="8888"
[GIN-debug] Listening and serving HTTP on :8888
2024-04-22T14:45:37+05:30       INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8081"}
2024-04-22T14:45:37+05:30       INFO    setup   starting manager
2024-04-22T14:45:37+05:30       INFO    Starting server {"kind": "health probe", "addr": "[::]:8082"}
2024-04-22T14:45:37+05:30       INFO    starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8081"}
2024-04-22T14:45:37+05:30       INFO    Starting EventSource    {"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module", "source": "kind source: *v1alpha1.Module"}
2024-04-22T14:45:37+05:30       INFO    Starting Controller     {"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module"}
2024-04-22T14:45:37+05:30       INFO    Starting workers        {"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module", "worker count": 1}
^C2024-04-22T16:52:07+05:30     INFO    Stopping and waiting for non leader election runnables
2024-04-22T16:52:07+05:30       INFO    shutting down server    {"path": "/metrics", "kind": "metrics", "addr": "[::]:8081"}
2024-04-22T16:52:07+05:30       INFO    Stopping and waiting for leader election runnables
2024-04-22T16:52:07+05:30       INFO    Shutdown signal received, waiting for all workers to finish     {"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module"}
2024-04-22T16:52:07+05:30       INFO    All workers finished    {"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module"}
2024-04-22T16:52:07+05:30       INFO    Stopping and waiting for caches
2024-04-22T16:52:07+05:30       INFO    Stopping and waiting for webhooks
2024-04-22T16:52:07+05:30       INFO    Wait completed, proceeding to shutdown the manager
make: *** [Makefile:159: start] Error 1
```

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, what do you mean by getting stuck on the same logs? After you run `make start`, you should see logs:
```
.
.
.
2024-04-22T13:43:36+02:00	INFO	setup	starting manager
2024-04-22T13:43:36+02:00	INFO	starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8081"}
2024-04-22T13:43:36+02:00	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8082"}
2024-04-22T13:43:36+02:00	INFO	Starting EventSource	{"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module", "source": "kind source: *v1alpha1.Module"}
2024-04-22T13:43:36+02:00	INFO	Starting Controller	{"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module"}
2024-04-22T13:43:36+02:00	INFO	Starting workers	{"controller": "module", "controllerGroup": "cyclops-ui.com", "controllerKind": "Module", "worker count": 1}
```
It will not log anything else until you start deploying new Modules. Have you tried starting the `cyclops-ui` and deploying a new module? You should then see a log that a new Module has been created. You can start the UI by following [this section](https://github.com/cyclops-ui/cyclops/blob/main/CONTRIBUTING.md#ui-cyclops-ui)

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit thanks for the explanation, the thing is I've contributed to observability projects like prometheus and grafana before and during building the code it behaves differently, I don't have much experience in contributing to projects like this one so I think I got confused.

There are some more things I need to clarify, since `make start` was executed successfully, the controller part is done right ? after starting the `cyclops-ui` do I also need to build the web part ?

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker, no worries. We are also working on our contributing docs, so feel free to ask/propose anything that might help you.

`make start` will start the backend part of Cyclops, which serves as a Kubernetes controller and a CRUD API. After that, you need to start the Cyclops frontend in the `cyclops-ui`, which connects to the mentioned backend.
That should be it. From here, you should be able to change the code and test it on your cluster.
Hope I helped. If you have any more questions, feel free to post them here.

**Comment by Sheikh-Abubaker** [comment]
> `make start` will start the backend part of Cyclops, which serves as a Kubernetes controller and a CRUD API. After that, you need to start the Cyclops frontend in the `cyclops-ui`, which connects to the mentioned backend. That should be it. From here, you should be able to change the code and test it on your cluster. Hope I helped. If you have any more questions, feel free to post them here.

Thank you @petar-cvit as of now I am stuck with the UI part, I ran `yarn install` inside `cyclops-ui` following `yarn start` but it throws this error due to which I'm having a hard time moving forward, I've been trying to fix it all day:

```
Failed to compile.

Module not found: Error: Can't resolve '/mnt/g/OpenSource/cyclops/Issue#203-Ignore-Notes-txt/cyclops/cyclops-ui/node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true' in '/mnt/g/OpenSource/cyclops/Issue#203-Ignore-Notes-txt/cyclops/cyclops-ui'
ERROR in Module not found: Error: Can't resolve '/mnt/g/OpenSource/cyclops/Issue#203-Ignore-Notes-txt/cyclops/cyclops-ui/node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true' in '/mnt/g/OpenSource/cyclops/Issue#203-Ignore-Notes-txt/cyclops/cyclops-ui'

webpack compiled with 1 error
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

**Comment by petar-cvit** [comment]
did you pull the latest main? I see that the sidebar menu is blue which we changed recently

**Comment by Sheikh-Abubaker** [comment]
> did you pull the latest main?

Yes I did

**Comment by petar-cvit** [comment]
This is really weird. I tried cloning your fork and ran `yarn install` and `yarn start` in the `cyclops-ui` repo and it worked (image below)

<img width="1509" alt="Screenshot 2024-04-22 at 20 23 10" src="https://github.com/cyclops-ui/cyclops/assets/72022639/ca80c2a7-93a5-4ade-ac41-e97954376fa0">

Can you try cloning again, I'm out of ideas

**Comment by Sheikh-Abubaker** [comment]
> This is really weird. I tried cloning your fork and ran `yarn install` and `yarn start` in the `cyclops-ui` repo and it worked (image below)
> 
> <img width="1509" alt="Screenshot 2024-04-22 at 20 23 10" src="https://github.com/cyclops-ui/cyclops/assets/72022639/ca80c2a7-93a5-4ade-ac41-e97954376fa0">
> 
> Can you try cloning again, I'm out of ideas

Yep that is weird, no worries let me clone it and try again.

**Comment by Sheikh-Abubaker** [comment]
## Tried cloning again this time and testing it the original code from main not the modified code that I wanted to test, though the compile was successful:
```
Compiled successfully!

You can now view cyclops-ui in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.17.184.159:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

webpack compiled successfully
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
```
## But it throws the same error in the UI:
 

![image](https://github.com/cyclops-ui/cyclops/assets/99421476/adc10778-2367-487d-a681-b9a9067ca70e)

![image](https://github.com/cyclops-ui/cyclops/assets/99421476/5e843c39-3b81-44f6-aa74-d077f3d8d4f9)

![image](https://github.com/cyclops-ui/cyclops/assets/99421476/f972f534-ad08-428e-8452-d9676a4a7024)

**Comment by petar-cvit** [comment]
We added another CRD but forgot to update CONTRIBUTING.md. Can you try running this command:
```
kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/main/install/chart/crds/cyclops-module.yaml \
  -f https://raw.githubusercontent.com/cyclops-ui/cyclops/main/install/chart/crds/template-auth-rule.yaml \
  -f https://raw.githubusercontent.com/cyclops-ui/cyclops/main/install/chart/crds/template-store.yaml
```

I updated the docs now. Thanks for noticing this

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit thanks for adding another CRD, it worked fine this time:

![image](https://github.com/cyclops-ui/cyclops/assets/99421476/dc013825-f572-4c16-b7f4-a5ed0932ec93)


## But when I proceeded with adding a new template it throws this error:
```
Error creating module
namespaces "cyclops" not found
```

![image](https://github.com/cyclops-ui/cyclops/assets/99421476/6f953e92-ae98-46d6-b7e1-61d8b9d96495)

**Comment by petar-cvit** [comment]
You can solve that with:
```
kubectl create namespace cyclops
```
Sorry for the inconvenience, will fix it in the CONTRIBUTING.md

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit please checkout #225 and let me know if it is up to mark
