### ISSUE TITLE
Rollback Page needs a `go back` button

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#211]
### The Problem
- When on the rollback page of a module, there is no way to return to your module page via the app itself (you can do so with the browser commands only). 

### Wanted Solution
- A button that lets you go back to the module page is needed on the page.

**Comment by Aniruddha775** [comment]
Hey I want to work on this issue. It would be helpful if you specify on which directory the file is located.

**Comment by KaradzaJuraj** [comment]
Great! The rollback feature is located in `components/pages/History.tsx`.
If you have any additional questions, let me know!

**Comment by KaradzaJuraj** [comment]
You can find an example of the `back` button in the `EditModule.tsx` file located in the `cyclops-ui/src/components/pages` directory.

**Comment by Aniruddha775** [comment]
Thanks for sharing the information.

**Comment by petar-cvit** [comment]
Hey @Aniruddha775, how is it going? Do you need any guidance?
