### ISSUE TITLE
Do sparse checkout when cloning a git repo

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#214]
**Is your feature request related to a problem? Please describe.**
When fetching templates from the git source, Cyclops clones the entire repo. It would be better, memory wise, to clone only the subtree of the repo.

**Comment by RohanMishra315** [comment]
Hey @petar-cvit we can use the git commands like git sparse and git depth and filter. Git sparse will be the specific one.

**Comment by Sheikh-Abubaker** [comment]
@RohanMishra315 are you working on this ?

**Comment by RohanMishra315** [comment]
> @RohanMishra315 are you working on this ?

Yes

**Comment by Sheikh-Abubaker** [comment]
Oh! Sorry to step in but I've been working on this issue a day or two after this issue was opened and I'm close to completion

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit can you please let me know in this repo where is that path variable located that is used to take input from user when adding a template, I went through `template.go` file but I'm still having doubts

**Comment by petar-cvit** [comment]
Thanks guys for picking this one up! I played around with this issue for a while, and I'm not sure it will help us.
The idea was to reduce the amount of content we clone when fetching a template by cloning just one subloder of a repository. I was hoping it would take less RAM, but even with sparse checkout, it seems like you still need to clone the whole repository and then sparse checkout that subfolder.
I'll close the issue for now, but if you find it to be useful feel free to comment it here and I'd be happy to discuss

**Comment by Sheikh-Abubaker** [comment]
> Thanks guys for picking this one up! I played around with this issue for a while, and I'm not sure it will help us. The idea was to reduce the amount of content we clone when fetching a template by cloning just one subloder of a repository. I was hoping it would take less RAM, but even with sparse checkout, it seems like you still need to clone the whole repository and then sparse checkout that subfolder. I'll close the issue for now, but if you find it to be useful feel free to comment it here and I'd be happy to discuss

Alright 👍
