### ISSUE TITLE
Sort fields from `values.schema.json`

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#228]
**Is your feature request related to a problem? Please describe.**
Cyclops uses an additional field `order` provided in the `values.schema.json` that allows users to set a custom order of fields in the object in their schemas (e.g. [here](https://github.com/cyclops-ui/templates/blob/ed31c853c3d04b736ab089eeaa36e631ed3b3bd8/demo-extended/values.schema.json#L101))
However, most templates won't have this field set and their children will have a random order. The scope of this issue is to order fields alphabetically if `order` is not provided.

Another possible case is that order is defined for just a subset of fields. Fields with a defined order should come before those without set order.

Example:
```json
{
  "properties": {
    "name": {
      ...
    },
    "scaling": {
      ...
    },
    "general": {
      ...
    },
    "probes": {
      ...
    },
    "networking": {
      ...
    }
    "owner": {
      ...
    },
  },
  "order": [
    "name",
    "general",
    "scaling"
  ]
}

```
Should be rendered in the to following order:
1. name
2. general
3. scaling
4. network
5. owner
6. probes

The first three are defined in the `order`, and the last three are sorted alphabetically. Ordered come before alphabetically sort ones.

**Describe the solution you'd like**
Add alphabetical sorting [here](https://github.com/cyclops-ui/cyclops/blob/3ad123f7cdf4ac2c93b1d64f50e123528a2a0027/cyclops-ctrl/internal/mapper/helm.go#L73)

**Comment by Sheikh-Abubaker** [comment]
Hey @petar-cvit I would like to work on this!!

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker thanks, but @RohanMishra315 already opened a PR for it

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker thanks, but @RohanMishra315 already opened a PR for it

@petar-cvit no worries!

**Comment by Tanmay-21** [comment]
@petar-cvit would like to give this a try.

**Comment by Tanmay-21** [comment]
Hey @petar-cvit, I have raised a PR for the requirement - #261

**Comment by petar-cvit** [comment]
Hey @Tanmay-21. @RohanMishra315 already has a PR for this, so let's wait to hear back from him about this issue
