### ISSUE TITLE
`cyctl`: delete Module command

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#239]
The scope of this issue is to implement the delete method for Modules custom resource. The command should look like:
```
cyctl delete module <module-name>
```

And it should simply call a method similarly to [this](https://github.com/cyclops-ui/cyclops/blob/75394437a7b9caac18964fe279958a3c04354891/cyctl/internal/get/modules.go#L13)

**Comment by yuvarajrece** [comment]
Can I work on this?
