### ISSUE TITLE
`cyctl`: delete TemplateAuthRule command

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#240]
The scope of this issue is to implement the delete method for TemplateAuthRule custom resource. The command should look like:
```
cyctl delete template-auth <template-auth-name>
```
And it should simply call a method similarly to [this](https://github.com/cyclops-ui/cyclops/blob/75394437a7b9caac18964fe279958a3c04354891/cyctl/internal/get/modules.go#L13)

**Comment by Sheikh-Abubaker** [comment]
@KaradzaJuraj I'd like to work on this
