### ISSUE TITLE
enchancement: UI improvement for the landing page 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [cyclops-ui/cyclops#244]
**Is your feature request related to a problem? Please describe.**
the ui of the present landing page has some good improvements that can be done, below are the screenshot that can be improved to match the modern ui standards and expectations.

1. navbar improvements are necessary 
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/c1bdc809-53a2-40dc-965e-48a1d9d079fb)

2. this part can be improved a lot to make it more explainable in a simple way 
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/0cb7dc3a-acc6-47a4-956d-6196e36daccd)

3. card ui improvements
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/08ca9b3d-bbe4-4a7f-9585-3bfe4ed77d08)

4. not correctly aligned
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/b76893a6-8be9-458d-9972-cf1a3ab4ba3b)

5. not correctly aligned + room for card improvement
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/943540fa-09e7-4cdd-99c7-604e31f1e87e)

6. improvements can be done to make it look more good 
![image](https://github.com/cyclops-ui/cyclops/assets/91052168/80933206-3376-4a84-b5df-f0445ef38cd8)

**Comment by petar-cvit** [comment]
Thanks @VineeTagarwaL-code. Can you open a PR for it and attach screenshots with the improved page?

**Comment by VineeTagarwaL-code** [comment]
yeah sure on it then thank you

**Comment by Wasiim105** [comment]
can i work on this

**Comment by hanshal101** [comment]
Hey @Wasiim105 appreciate for your excitement, but I think @VineeTagarwaL-code is already working on this.

**Comment by vinitvijal** [comment]
can I work on this

**Comment by petar-cvit** [comment]
Closing this one, if you have ideas to improve our landing page, feel free to open another issue
