### ISSUE TITLE
Focused UI fields are visible over header

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#253]
**Describe the bug**
When a field on the  `New Module` / `Edit Module` is in focus, and you scroll down, the field in focus goes over the header.

https://github.com/cyclops-ui/cyclops/assets/72022639/6fbc4f0d-f02d-4735-a64b-4aa5c354f605

**To Reproduce**
1. Install templates into your cluster
    `kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/main/install/demo-templates.yaml`
2. Select the `demo-extended` template since its the longest template
3. Expand nested fields as in the video above so you can scroll down.
4. Select one field as if you would change it's value
5. If you scroll down, you should see the field is over the header.

**Expected behavior**
Fields shouldn't go over the header.

**Proposed solution**
We can change the z-index of those components or set  `overflow: hidden`

**Comment by AKHIL-DyC** [comment]
can i work on this issue

**Comment by hanshal101** [comment]
Go on @AKHIL-DyC !

**Comment by AKHIL-DyC** [comment]
#254

**Comment by hanshal101** [comment]
Hey @AKHIL-DyC thanks for your contribution can you add the Issue tag on your PR description, something like this:

```
Fixes (#)253 (note dont add the bracket around the hash)
```
