### ISSUE TITLE
Dynamic number of Module list columns

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#255]
**Is your feature request related to a problem? Please describe.**
When you open the `/modules` of Cyclops UI, you will see modules listed as cards in three columns regardless of the size of the screen. It would be more readable if the number of columns was dynamic based on the size of the screen. On large screens, the cards are too wide, while on narrower screens, they are squeezed in.

Wider screen:
![Screenshot 2024-05-03 at 15 38 30](https://github.com/cyclops-ui/cyclops/assets/72022639/34266b05-6351-4bc5-bb70-0ab7d8204fd6)

Narrow screen:
![Screenshot 2024-05-03 at 15 41 36](https://github.com/cyclops-ui/cyclops/assets/72022639/1863994f-52dc-493a-8ea8-944426715c1f)

**Describe the solution you'd like**
Make the number of columns dynamic based on the screen width

**Comment by Tapasvi48** [comment]
<img width="1440" alt="Screenshot 2024-05-14 at 12 46 32 AM" src="https://github.com/cyclops-ui/cyclops/assets/115564323/e0bca752-e539-49d7-bdd3-ce70a7c7bb17">
<img width="1440" alt="Screenshot 2024-05-14 at 12 45 50 AM" src="https://github.com/cyclops-ui/cyclops/assets/115564323/79b9a728-13f2-42e5-bbc0-730efc096594">
<img width="1440" alt="Screenshot 2024-05-14 at 12 45 47 AM" src="https://github.com/cyclops-ui/cyclops/assets/115564323/8474fa29-3d73-4fb6-82dc-e8753db7477c">
How does this look ?

**Comment by petar-cvit** [comment]
Hey @Tapasvi48, looks good! Can you open a PR for it?

**Comment by Tapasvi48** [comment]
hey i have linked the pr for the issue please check it
