### ISSUE TITLE
Disable `Edit` if no fields are changed

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#256]
**Is your feature request related to a problem? Please describe.**
When editing Module values, you can save the change without altering any values. This triggers a new entry in the `Rollback` view and creates more generations than necessary.

Scope of the issue is to disable the `Save` button on the `Edit` page if no values are updated.

Example of a History entry that didn't change any fields:
<img width="807" alt="Screenshot 2024-05-02 at 20 07 39" src="https://github.com/cyclops-ui/cyclops/assets/72022639/20132433-bd81-4b80-9d07-8a0c16c7ea08">

**Comment by AKHIL-DyC** [comment]
working on it

**Comment by hanshal101** [comment]
Go on @AKHIL-DyC !
