### ISSUE TITLE
Implement resource details for PersistentVolumeClaims

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#258]
**Is your feature request related to a problem? Please describe.**
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment form default namespace called `demo-app` you would call:
`/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default`

The goal of the issue is to support PersistentVolumeClaims on the same endpoint. The endpoint for fetching PVC data would look like this: `/resources?group=&version=v1&kind=PersistentVolumeClaim&name=<name>&namespace=<namespace>`.

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/a648a84971c3ffaed600d20159618a55a62c31ea/cyclops-ctrl/internal/controller/modules.go#L516), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/cdb675623c58e4389c9b1abeb9b041d024e6ed7f/cyclops-ctrl/internal/cluster/k8sclient/client.go#L212).

In the response, you can add the size of the PVC, access mode, and anything else you would find useful.

**Comment by Tanmay-21** [comment]
Hi @petar-cvit can you please assign this to me. Would love to contribute!

**Comment by petar-cvit** [comment]
Hey @Tanmay-21, sure thing!

**Comment by Tanmay-21** [comment]
Hey @petar-cvit, I have raised a PR for required code changes - #259
Pls Review and also guide me how can I test this with ease.
