### ISSUE TITLE
Color of the Collapse component goes out of border

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#269]
**Describe the bug**
To represent each K8s resource deployed for a Module we are using ant design [Collapse.Panel](https://github.com/cyclops-ui/cyclops/blob/ec164f960cde9a37212200e6f21b9ff592adb448/cyclops-ui/src/components/pages/ModuleDetails.tsx#L476). The issue is that the color is going out of the component on the upper corner and should be contained as it is on the bottom corners.

The corner where the color goes outside the component is highlighted with a red circle on the picture below
<img width="273" alt="Screenshot 2024-05-16 at 13 45 25" src="https://github.com/cyclops-ui/cyclops/assets/72022639/e0834fb6-3f43-4618-83c2-e0d5ac22a83c">

**To Reproduce**
1. Start a Cyclops instance by following [this](https://cyclops-ui.com/docs/installation/install/manifest)
2. Hit `Add module`
3. Select `demo-template` template and create a Module with any values
4. You should be redirected to a page that shows all resources created for that Module, and you should see the issue with colors described above in the `Resources` section.

**Expected behavior**
Upper corners should be the same as the bottom corners

**Comment by petar-cvit** [comment]
In the upper left corner in the image, the color goes over the rounded edge, and that doesn't happen on the bottom left corner. It's more visible when the resource is selected because the `Colapse.Panel` color is darker

<img width="239" alt="Screenshot 2024-05-16 at 16 57 15" src="https://github.com/cyclops-ui/cyclops/assets/72022639/81305d3a-8376-4eee-a546-631cc50b2a44">

**Comment by AKHIL-DyC** [comment]
working on it

**Comment by petar-cvit** [comment]
Sure thing @AKHIL-DyC

**Comment by AKHIL-DyC** [comment]
![Uploading 240516_23h34m15s_screenshot.png…]()

**Comment by petar-cvit** [comment]
@AKHIL-DyC can you try reuploading the image?
![Screenshot 2024-05-16 at 20 17 56](https://github.com/cyclops-ui/cyclops/assets/72022639/f71fd2d9-5eac-4e71-a767-d386a8a67f4b)

**Comment by AKHIL-DyC** [comment]
![Uploading 240516_23h53m39s_screenshot.png…]()

**Comment by AKHIL-DyC** [comment]
![240516_23h53m39s_screenshot](https://github.com/cyclops-ui/cyclops/assets/119416316/127a6215-6044-47c5-9729-5f0aef0585c7)
fix
