### ISSUE TITLE
Implement UI component for PersistentVolumeClaims

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#270]
**Is your feature request related to a problem? Please describe.**
Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The ccope of this issue is to support `PersistantVolumeClaims`. The new PVC component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a PVC by calling the backend on

```
/api/resources?group=&version=v1&kind=PersistentVolumeClaim&name=<name>&namespace=<namespace>
```

To be able to test this, you will need to use a template that supports PVCs. You should add the following template and create a Module from it:
```yaml
repo: https://github.com/cyclops-ui/templates
path: redis
version: test-pvc-ui
```

**Comment by doncicuto** [comment]
Hi @petar-cvit, I'd like to contribute to this project, could you assign this issue to me? Thanks!

**Comment by petar-cvit** [comment]
Hey @doncicuto, sure thing! Let us know if you have any questions
