### ISSUE TITLE
Implement resource details for Secrets

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#271]
**Is your feature request related to a problem? Please describe.**
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment form default namespace called demo-app you would call:
/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default

The goal of the issue is to support Secrets on the same endpoint. The endpoint for fetching Secret data would look like this: /resources?group=&version=v1&kind=Secret&name=<name>&namespace=<namespace>

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/a648a84971c3ffaed600d20159618a55a62c31ea/cyclops-ctrl/internal/controller/modules.go#L516), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/cdb675623c58e4389c9b1abeb9b041d024e6ed7f/cyclops-ctrl/internal/cluster/k8sclient/client.go#L212).

You can add all the keys of the Secret in the response but not the values. We don't want to show the values since they are secret.

Refer to this PR on adding new types #259

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit I would like to take this issue

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, you can take this one

**Comment by Sheikh-Abubaker** [comment]
> Hey @Sheikh-Abubaker, you can take this one

Thanks
