### ISSUE TITLE
I can't access the cyclops from outside 

### ISSUE THREAD

**Issue by Asakaigg** [cyclops-ui/cyclops#273]
![image](https://github.com/cyclops-ui/cyclops/assets/165806253/3a0109db-5c70-455a-b388-f40d985d0464)
I have installed cyclops on my self kubernetes but I can't access it from outside.
By editing the service , I have changed the type as NodePort from loadbalancing but I can't access the dashboard 
![image](https://github.com/cyclops-ui/cyclops/assets/165806253/ece3f10c-47bf-4d27-8e62-d63aa65e267d)

**Comment by petar-cvit** [comment]
@Asakaigg  Can you try installing Cyclops with:
```bash
kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/v0.5.0/install/cyclops-install.yaml && 
kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/v0.5.0/install/demo-templates.yaml
```

And then try port-forwarding

**Comment by Asakaigg** [comment]
sorry 
it is my node issue 
thanks for your help
