### ISSUE TITLE
Reset State of Delete Resource Modals 

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#283]
## Problem
The delete resource modal saves the state across resources.

### Steps to reproduce
1. Deploy `redis-demo` template and enable replication
2. Edit the module, disable replication and save
3. Service and Deployment replicas are now marked as safe for deletion
4. Delete the Service (or Deployment) → you will have to input the name of the resource
5. Now delete the Deployment (or Service) → you will see that the previous input is already here

<img width="531" alt="Screenshot 2024-05-21 at 14 08 43" src="https://github.com/cyclops-ui/cyclops/assets/101581637/5bab5bb8-624d-405b-ba84-1d0c046d926d">
<img width="522" alt="Screenshot 2024-05-21 at 14 09 37" src="https://github.com/cyclops-ui/cyclops/assets/101581637/642736f2-007f-4ee1-9699-bb036c5c7696">

## Solution
The modal state needs to be reset after it closes by clicking the Delete button or the X button.
In `cyclops-ui/src/components/pages/ModuleDetails.tsx` the `handleCancelDeleteResource` and `deleteResource` functions need to update `deleteResourceVerify` to an empty state.

**Comment by Wasiim105** [comment]
@KaradzaJuraj I would like to take this issue. Can you assign me ?

**Comment by KaradzaJuraj** [comment]
Of course @Wasiim105 !
