### ISSUE TITLE
Duplicate Error Warning on Templates Screen

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#284]
## Problem

When you try to add a new template to Cyclops and fail, the error is displayed both on the modal and in the background (as the picture below shows). This is unnecessary, and we should only display the error on the modal.

![Screenshot 2024-05-21 at 14 24 24](https://github.com/cyclops-ui/cyclops/assets/101581637/a07768fd-51b2-4dcf-bfd5-a4cb62f5aaf6)

### Solution

Implement a separate error state for the modal in `cyclops-ui/src/components/TemplateStore/TemplateStore.tsx`

The `Alert` on line 278 represents the background error and the `Alert` on line 359 represents the error shown on the modal.

### Alternative Solution

Implement error notifications similar to this [PR](https://github.com/cyclops-ui/cyclops/pull/280)

**Comment by KaradzaJuraj** [comment]
Of course @ArnavK-09 !

**Comment by ArnavK-09** [comment]
![image](https://github.com/user-attachments/assets/a4876369-2434-4bdc-92b7-29beb6193c29)
