### ISSUE TITLE
When searching for deployed modules ,show 

### ISSUE THREAD

**Issue by AKHIL-DyC** [cyclops-ui/cyclops#286]
**Describe the bug**
When searching for deployed modules ,it shows blank if not found,
This would confuse the user thinking it has not been loaded.
he might think this is network issue
**To Reproduce**
1. Go to 'modules'
2. Click on 'search bar'
3. type a module that is not present 
4. See blank response

**Expected behavior**
show notfound card
**Screenshots**
![240522_02h32m12s_screenshot](https://github.com/cyclops-ui/cyclops/assets/119416316/d24fa3e4-0116-41d4-bc95-896c795c6fbc)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AKHIL-DyC** [comment]
@petar-cvit  i made a previous pull request which closes other issue ,this pull request has both the change

**Comment by petar-cvit** [comment]
@AKHIL-DyC  Thanks for raising the issue. Will assign this one to you, but please separate the changes into two PRs. It will be easier to track our changes later on.

**Comment by AKHIL-DyC** [comment]
> @AKHIL-DyC Thanks for raising the issue. Will assign this one to you, but please separate the changes into two PRs. It will be easier to track our changes later on.

ya i have reverted ,now this has only changes related to this pr,,will change the card to what you suggested
