### ISSUE TITLE
`cyctl`:  Implement a `describe` method for Modules / TemplateStore / TemplateAuthRules

### ISSUE THREAD

**Issue by siddhantprateek** [cyclops-ui/cyclops#291]
**Is your feature request related to a problem? Please describe.**
We need to implement a describe method for Modules, TemplateStore, TemplateAuthRules custom resource. The command structure should be:

```bash
cyctl describe module <module-name> 
```

**Would you like to work on this issue?**
Yes

**Comment by petar-cvit** [comment]
hey @siddhantprateek thanks for the issue. I would like the `describe` command to return a yaml and print it in the terminal.  Feel free to pick it up, I'll assign you here
