### ISSUE TITLE
Implement resource details for DaemonSet

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#302]
Is your feature request related to a problem? Please describe.
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment form default namespace called demo-app you would call:
/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default

The goal of the issue is to support DaemonSets on the same endpoint. The endpoint for fetching DaemonSet data would look like this: /resources?group=apps&version=v1&kind=DaemonSet&name=&namespace=

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/a648a84971c3ffaed600d20159618a55a62c31ea/cyclops-ctrl/internal/controller/modules.go#L516), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/cdb675623c58e4389c9b1abeb9b041d024e6ed7f/cyclops-ctrl/internal/cluster/k8sclient/client.go#L212).

You can add data about pods and its status similar to what we are doing with [Deployments](https://github.com/cyclops-ui/cyclops/blob/19726aed0828c999fb17e84100ebea03490666ee/cyclops-ctrl/internal/cluster/k8sclient/client.go#L443).

Refer to this PR on adding new types https://github.com/cyclops-ui/cyclops/pull/259

**Comment by FengMeizuo** [comment]
This sounds interesting. Can I take this one ?

**Comment by petar-cvit** [comment]
Hey @FengMeizuo, sure!

**Comment by petar-cvit** [comment]
You can use the following template to create a DaemonSet:
```
repo: https://github.com/cyclops-ui/templates
path: demo
version: test-daemonset-endpoint
```
