### ISSUE TITLE
Templates Status Check

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#303]
## Problem

We want to implement a button that initiates a status check for templates. This will allow us to check if the reference is still valid and if the chart still exists in the specified URL (it hasn’t been moved or deleted).

## Solution

Implement a button that will perform a status check. Implement it as a new Table column in the `cyclops-ui/src/pages/TemplateStore/TemplateStore.tsx` and place it before the `Edit` and `Delete` buttons. You can find an icon for the new button in the [AntDesign Icons package](https://ant.design/components/icon).

![Screenshot 2024-04-29 at 17 03 34](https://github.com/cyclops-ui/cyclops/assets/101581637/a5dc4797-16b6-4244-bc21-fac1917ba1af)

The button should implement similar functionality as in the [Reference Check issue](https://github.com/cyclops-ui/cyclops/issues/233). While the status check is being performed, implement a visual cue (perhaps change color and rotate the icon ?) similar to how GitHub has when requesting PR reviews.

![Screenshot 2024-05-16 at 15 16 55](https://github.com/cyclops-ui/cyclops/assets/101581637/ab7d1da5-a25b-427e-b937-8b748b6d5822)

On the backend, update the `EditTemplatesStore` to call the `GetTemplate` function, which will perform the reference check. You can find these functions in `cyclops-ctrl/internal/controller/templates.go`

**Comment by Sheikh-Abubaker** [comment]
I would like to give it a try

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, sure thing

**Comment by Sheikh-Abubaker** [comment]
> Hey @Sheikh-Abubaker, sure thing

@petar-cvit would it be fine if I take some time in proposing a fix for this ? I know go but I'd have to learn the other stacks and then I'll open a PR.

**Comment by petar-cvit** [comment]
No problem, take your time. If there is something we can help out, feel free to post it here

**Comment by Sheikh-Abubaker** [comment]
> No problem, take your time. If there is something we can help out, feel free to post it here

Thank you for your support, I'll surely post my questions here, if any follows.

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit Update on the issue, I have successfully developed the feature, just testing and trying out some CSS, will open the PR in a while.
