### ISSUE TITLE
Helm chart doesn't follow best-practices

### ISSUE THREAD

**Issue by cwrau** [cyclops-ui/cyclops#310]
**Describe the bug**
The helm chart creates a namespace and the service is a LoadBalancer by default.

**To Reproduce**
1. Install the helm chart

**Expected behavior**
No namespace to be created, as well as the service to be a normal ClusterIP service.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: 0.3.3

**Additional context**
It is best-practice to not create namespace, or if needed only if they are part of the application, which is rarely, and not here, the case. Helm/The user is supposed to take care of that.

The default values should work out-of-the-box as much as possible, and creating a LoadBalancer ~by default just~ incurs cost for the user ~which they're probably going to disable anyways, as they are going to use an ingress.~

Ok, that is hardcoded and no ingress is available, this should be implemented.

**Comment by petar-cvit** [comment]
Hey @cwrau, thanks for raising this. We updated to `ClusterIP` in our install manifest but didn't do it for the Helm chart.

If you are up for it, you can raise a PR for it

**Comment by petar-cvit** [comment]
Hey, updated the chart to version v0.7.3 of Cyclops and fixed the mentioned issues here https://github.com/cyclops-ui/cyclops/pull/391

**Comment by cwrau** [comment]
This should've been a breaking change, i.e. major release, as now the namespace will be deleted

Or, even better, you could've first added `helm.sh/resource-policy: keep` to the namespace and then create a breaking change in deleting it, that way it would've just stayed there

**Comment by petar-cvit** [comment]
I agree, but I decided not to bump the major version of the chart since it's not that widely used, and we haven't documented it yet as a way to install Cyclops.

On the other hand, the fact that we are tagging the helm chart with the same value as the `appVersion` is not the best practice which we will stop in future releases
