### ISSUE TITLE
Implement UI component for DaemonSets

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#315]
Is your feature request related to a problem? Please describe.
Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The scope of this issue is to support Daemonsets. The new DeamonSet component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a daemonset by calling the backend on

/api/resources?group=apps&version=v1&kind=DaemonSet&name=<name>&namespace=<namespace>
To be able to test this, you will need to use a template that supports secrets. You should add the following template and create a Module from it:
```
repo: https://github.com/cyclops-ui/templates
path: demo
version: test-daemonset-endpoint
```

You can render a similar component to the one we have for [Deployments](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/Deployment.tsx)

**Comment by doncicuto** [comment]
Hi @petar-cvit if you're happy with my recent PR you may assign this issue to me. Thanks!

**Comment by FengMeizuo** [comment]
Hello @doncicuto, I already started working on this issue, my bad, I didn't comment anything. Is it possible that you allow me to finish this issue please ?

**Comment by petar-cvit** [comment]
@FengMeizuo, you can take this one since you implemented the backend endpoint for it. Just make sure for future issues to let us know you would like to take them so we can assign them properly.

@doncicuto, I just saw your PR for PVCs, and it looks good! I just left two questions in the comments. Can you leave this issue to @FengMeizuo? You can take a similar issue but for secrets next #297. Let me know if you want me to assign you to it on the secrets issue.

Thanks both! ❤️

**Comment by doncicuto** [comment]
Sure, no problem, @FengMeizuo go ahead
