### ISSUE TITLE
Add output flag to cyctl create

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#322]
**Is your feature request related to a problem? Please describe.**
`cyctl create` currently creates resources directly in the cluster. The scope of the issue is to add `--output` flag that would print yaml or json so users can see what is going to be deployed and use it outside cyctl.

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, sure thing

**Comment by thebigbone** [comment]
The `create modules` is still not implemented, so this is just for the templates right?

**Comment by hanshal101** [comment]
Hey @Sheikh-Abubaker are you still working on this, if not then I can pick up.

**Comment by Sheikh-Abubaker** [comment]
> Hey @Sheikh-Abubaker are you still working on this, if not then I can pick up.

Yes I am!

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker do you have any updates on the issue

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker do you have any updates on the issue

I was a bit occupied at Grafana, would it be fine it I post some updates in the coming week ?

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker sure thing. Post any updates here

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit I have started working on this one, going through docs and resources to learn more about cyctl, sorry for the delay at first I was occupied at Grafana and as of now a bit sick, but I am starting to get back on the track!

**Comment by Sheikh-Abubaker** [comment]
Hey there @petar-cvit I've this habit of debugging any code with my custom print statements in order to understand the flow better 😅, I tried adding the custom print statement [here](https://github.com/cyclops-ui/cyclops/blob/5388d7cc91714994a5c7c33a576633685870a9ba/cyctl/internal/create/modules.go#L31), but I wasn't able to see that reflect in the backend logs inside `/cyclops-ctrl` where I ran `make start`.

## I only saw this in the backend even after adding the custom print statement:

```
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/sheikhabubaker/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222
2024-08-23T18:30:46+05:30       INFO    KubeAPIWarningLogger    unknown field "status.iconURL"
2024-08-23T18:30:46+05:30       INFO    KubeAPIWarningLogger    unknown field "status.managedGVRs"
2024-08-23T18:30:46+05:30       INFO    reconciler      upsert module   {"namespaced name": {"name":"test-app-1","namespace":"cyclops"}}
2024-08-23T18:36:18+05:30       INFO    reconciler      upsert module   {"namespaced name": {"name":"my-module","namespace":"cyclops"}}
2024-08-23T18:36:19+05:30       INFO    reconciler      upsert module   {"namespaced name": {"name":"my-module","namespace":"cyclops"}}
```


I wanted to see the exact part of the code, which is triggered when I run `cyctl create`.
## Logs from my machine:

```
sheikhabubaker@DESKTOP-TFVM3PT:/mnt/c/Users/sheik/Templates/demo$ cyctl create module my-module -f values.yaml --repo='https://github.com/cyclops-ui/templates' --path='demo' --version='main'
my-module created successfully.
```

![image](https://github.com/user-attachments/assets/88e689a4-657b-4075-ae9e-dcf794db9eb7)

**Comment by petar-cvit** [comment]
Hey @Sheikh-Abubaker, if you are adding print statements in the `/cyctl` it wont be visible in cyclops-ctrl logs. cyclops-ctrl is an app that serves as the backend to Cyclops, and cyctl is the cli.

You should recompile cyctl by running `go build -o cyctl main.go` from the `/cyctl` and then run it with `./cyctl create module ...`

**Comment by Sheikh-Abubaker** [comment]
> Hey @Sheikh-Abubaker, if you are adding print statements in the `/cyctl` it wont be visible in cyclops-ctrl logs. cyclops-ctrl is an app that serves as the backend to Cyclops, and cyctl is the cli.

I was thinking the same, but thanks for clarification!

> 
> You should recompile cyctl by running `go build -o cyctl main.go` from the `/cyctl` and then run it with `./cyctl create module ...`

Allright!

**Comment by Sheikh-Abubaker** [comment]
Hey @petar-cvit is this kinda something expected ?

```
$ ./cyctl create module my-module -f values.yaml --repo='https://github.com/cyclops-ui/templates' --path='demo' --version='main' --output=yaml
createModule func in modules.go file
---
apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  creationTimestamp: null
  name: my-module
  namespace: cyclops
spec:
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 1
    service: true
    version: 1.14.2
status:
  reconciliationStatus:
    reason: ""
    status: ""

$ ./cyctl create module my-module -f values.yaml --repo='https://github.com/cyclops-ui/templates' --path='demo' --version='main' --output=json
createModule func in modules.go file
{
  "kind": "Module",
  "apiVersion": "cyclops-ui.com/v1alpha1",
  "metadata": {
    "name": "my-module",
    "namespace": "cyclops",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "repo": "https://github.com/cyclops-ui/templates",
      "path": "demo",
      "version": "main"
    },
    "values": {
      "image": "nginx",
      "name": "demo-app",
      "replicas": 1,
      "service": true,
      "version": "1.14.2"
    }
  },
  "status": {
    "reconciliationStatus": {
      "status": "",
      "reason": ""
    }
  }
}

$ ./cyctl create module my-module -f values.yaml --repo='https://github.com/cyclops-ui/templates' --path='demo' --version='main'
createModule func in modules.go file
my-module created successfully.
```

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker yeah looks good. You can open a PR for it

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker yeah looks good. You can open a PR for it

@petar-cvit I'm onto it, just debugging a bit more, will open the PR soon.

**Comment by Sheikh-Abubaker** [comment]
Hey @petar-cvit could you please tell a little about templateauthrule and it's use cases.
