### ISSUE TITLE
Implement resource details for Jobs

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#339]
Is your feature request related to a problem? Please describe.
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment form default namespace called demo-app you would call:
`/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default`

The goal of the issue is to support **Jobs** on the same endpoint. The endpoint for fetching Jobs data would look like this:
```
/resources?group=batch&version=v1&kind=Job&name=<name>&namespace=<namespace>
```

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/a648a84971c3ffaed600d20159618a55a62c31ea/cyclops-ctrl/internal/controller/modules.go#L516), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/cdb675623c58e4389c9b1abeb9b041d024e6ed7f/cyclops-ctrl/internal/cluster/k8sclient/client.go#L212).

You can add data about pods a Job is managing and its status similar to what we are doing with [Deployments](https://github.com/cyclops-ui/cyclops/blob/19726aed0828c999fb17e84100ebea03490666ee/cyclops-ctrl/internal/cluster/k8sclient/client.go#L443).

Refer to this PR on adding new types https://github.com/cyclops-ui/cyclops/pull/259

To be able to test this, you will need to use a template that supports jobs. You should add the following template and create a Module from it:
```
repo: https://github.com/cyclops-ui/templates
path: demo-job
version: test-job-endpoint
```

**Comment by patelajay745** [comment]
Hello,

I would like to solve this issue.

Thank you.

**Comment by petar-cvit** [comment]
Hey @patelajay745, sure!
