### ISSUE TITLE
Filter Deployment logs

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#341]
**Is your feature request related to a problem? Please describe.**
Cyclops shows logs for running pods [here](https://github.com/cyclops-ui/cyclops/blob/11185d7871fc0957ffab78bfd5f54d783fbb5fc3/cyclops-ui/src/components/k8s-resources/Deployment.tsx#L114). Scope of the task is to add a search for logs that you can use to filter out the log you are looking for.

**Describe the solution you'd like**
Add a search bar to the top of the logs modal and show all logs that contain the search input.

**Comment by doncicuto** [comment]
Hi @petar-cvit would the search box that comes with React Ace would fit your need?

![image](https://github.com/cyclops-ui/cyclops/assets/30386061/c92d4a0a-bad7-41a3-8e64-9d52ec69ea1f)

**Comment by petar-cvit** [comment]
@doncicuto Actually yeah, I actually searched for something out of the box like this, but didn't find it. Exactly what we need. Could you open a PR for it?

**Comment by doncicuto** [comment]
Perfect @petar-cvit you can assign the issue to me then and do you want the Search button to show for every React Ace editor or just for the one for Deployment logs?

**Comment by petar-cvit** [comment]
Just the one with the logs will do

**Comment by petar-cvit** [comment]
Hey @doncicuto, do you have any updates on the issue?

**Comment by doncicuto** [comment]
Next week I'll prepare a PR, sorry for the delay, busy summer!

**Comment by Sheikh-Abubaker** [comment]
@quest-bot embark

**Comment by Sheikh-Abubaker** [comment]
@petar-cvit I'm taking this one!

**Comment by Sheikh-Abubaker** [comment]
Hey @petar-cvit a lot has changed since you opened this issue, could you please let me know where this deployment code is located at, the reference you mentioned in the description aren't there any more in the main.

**Comment by Sheikh-Abubaker** [comment]
Would something like this do the job @petar-cvit ? I just tested it locally.

https://github.com/user-attachments/assets/eb3de279-c195-482c-af0b-8efd85c1e1fd

**Comment by petar-cvit** [comment]
@Sheikh-Abubaker thanks! Can you check if we can implement something similar to https://github.com/cyclops-ui/cyclops/issues/341#issuecomment-2205549708 since it looks more clean in the UI and seems like it supports regex and casing in the search?

**Comment by Sheikh-Abubaker** [comment]
@quest-bot loot #341
