### ISSUE TITLE
Implement a restart endpoint

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#342]
**Is your feature request related to a problem? Please describe.**
To allow users to restart their workloads, cyclops-ctrl should expose a restart endpoint. You can register the endpoint and its handler function [here](https://github.com/cyclops-ui/cyclops/blob/5668c95e19d4e39a5c6130ca4245a497095fe861/cyclops-ctrl/internal/handler/handler.go#L83).

The endpoint should receive the group, version, kind, name and the namespace of the resource that needs to be restarted. You can fetch those similarly to how it was done [here](https://github.com/cyclops-ui/cyclops/blob/5668c95e19d4e39a5c6130ca4245a497095fe861/cyclops-ctrl/internal/controller/modules.go#L562). You can also check this link on how to restart a resource using go-client [here](https://stackoverflow.com/questions/61335318/how-to-restart-a-deployment-in-kubernetes-using-go-client).

Scope of the issue is implementing **only** the backend endpoint. Frontend part will be implemented separately.

**Comment by patelajay745** [comment]
I would like to give try on it.

**Comment by patelajay745** [comment]
What should an endpoint look like? I understand the underlying process, but what should the endpoint's response be?

**Comment by petar-cvit** [comment]
Hey @patelajay745, response of the endpoint can simply be 200 OK without the body if there was no error, or 500 Internal server error with the error in the response body. You can map the error in the response using `dto.NewError` ([example here](https://github.com/cyclops-ui/cyclops/blob/c04f5a6a82c76a31f4ee33e7dea1e5439e72108d/cyclops-ctrl/internal/controller/modules.go#L58))

**Comment by patelajay745** [comment]
Ok. Got it about response. How should endpoint look like?

**Comment by patelajay745** [comment]
Got it . Thanks
