### ISSUE TITLE
Expose modules errors on API endpoint

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#344]
**Is your feature request related to a problem? Please describe.**
Each module renders K8s resources from a template. While doing that, some errors can occur. Those errors are already present on the CRD, but still need to be mapped to the DTO model.

**Describe the solution you'd like**
You will need to add the errors field [here](https://github.com/cyclops-ui/cyclops/blob/aadf667833267684b5152418a332a558478179c1/cyclops-ctrl/internal/models/dto/modules.go#L3) and  map it in the [mapper function](https://github.com/cyclops-ui/cyclops/blob/aadf667833267684b5152418a332a558478179c1/cyclops-ctrl/internal/mapper/modules.go#L39).

**Comment by doncicuto** [comment]
Hi @petar-cvit can I take this issue?

**Comment by petar-cvit** [comment]
Hey @doncicuto, thanks

**Comment by doncicuto** [comment]
Hi @petar-cvit I've unassign this issue to me as I can't see a clear path for this. I'll finish my pending PR first and try to revisit it later

**Comment by petar-cvit** [comment]
Hey @patelajay745, sure thing

**Comment by patelajay745** [comment]
Hello @petar-cvit . Could not get the requirement? Could you please elaborate?

Thank you

**Comment by petar-cvit** [comment]
The goal of the issue is to add the [ReconciliationStatus](https://github.com/cyclops-ui/cyclops/blob/7495c0b97c79c77140877b90cc1b64e69a505e3d/cyclops-ctrl/api/v1alpha1/module_types.go#L58) to the response when backend is requested for a specific Module [here](https://github.com/cyclops-ui/cyclops/blob/eefe9cc059770978c5e29e71dab51338a5e168f9/cyclops-ctrl/internal/controller/modules.go#L46). You will need to add the status to the response and map it from the Module struct

**Comment by petar-cvit** [comment]
Hey @patelajay745, do you have any updates on the issue? Let me know if you have any questions

**Comment by patelajay745** [comment]
I am not sure. Is this what I'm supposed to do?

![Screenshot 2024-08-19 at 9 58 58 PM](https://github.com/user-attachments/assets/2296da39-c20b-454f-bfe9-3110a82cfc05)

**Comment by petar-cvit** [comment]
@patelajay745  looks good, but can we not import v1alpha1 package, but create a new dto model? You can open a PR so we can comment there, it will be easier to talk over code 😄
