### ISSUE TITLE
Scope cyclops controller to a namespace

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#345]
**Is your feature request related to a problem? Please describe.**
Kubernetes controllers listen to changes on certain resource types. In the case of Cyclops, the controller is listening to changes on the Module resource. Currently, modules can be deployed to any namespace, but the controller should only take those deployed to the `cyclops` namespace.

The goal of the issue is to scope the controller just to a single namespace. By default it should be `cyclops`, but a user should be able to configure it using an environment variable.

You can check how to scope a controller to a single namespace [here](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/). Also, the definition of our controller options is [here](https://github.com/cyclops-ui/cyclops/blob/ba0a74443cfb82ffc05bf9ba58b22a4d27fbb1ee/cyclops-ctrl/cmd/main/main.go#L90).

**Comment by shubhamch71** [comment]
Hii , I would like to work on this !!!
/assign

**Comment by petar-cvit** [comment]
Hey @shubhamch71, sure!
