### ISSUE TITLE
UI representation for `Jobs`

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#350]
### Problem

Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The scope of this issue is to support `Jobs`. 

The new `Job` component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a `Job` by calling the backend on

```bash
/api/resources?group=batch&version=v1&kind=Job&name=&namespace=
```

### Solution

Reference this PR for BE implementation: https://github.com/cyclops-ui/cyclops/pull/349
You can render a similar component to the one we have for [Deployments](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/Deployment.tsx).

**Comment by samarsrivastav** [comment]
is it similar to #351 ?? i would like to take up the issue
