### ISSUE TITLE
UI representation for `CronJobs`

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#351]
### Problem
Some K8s components are supported to have a custom UI component, and those can be found [here](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources). The scope of this issue is to support `CronJobs`. 

The new `CronJob` component should be similar to other components we already have, so feel free to check the existing ones out. You can fetch the data about a `CronJob` by calling the backend on

```bash
/api/resources?group=batch&version=v1&kind=CronJob&name=&namespace=
```

### Solution
Reference this PR for BE implementation: https://github.com/cyclops-ui/cyclops/pull/346
You can render a similar component to the one we have for [Deployments](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/Deployment.tsx).

**Comment by samarsrivastav** [comment]
are you referring to ` function fetchConfigMap() {
    axios
      .get(`/api/resources`, {
        params: {
          group: ``,
          version: `v1`,
          kind: `ConfigMap`,
          name: name,
          namespace: namespace,
        },
      })
      .then((res) => {
        setConfigMap(res.data);
      })
      .catch((error) => {
        setError(mapResponseError(error));
      });
  }` this fetch here to be updated.


please elaborate the issue. I would Love to work on it.

**Comment by petar-cvit** [comment]
Hey @samarsrivastav, sure! Alongside other components in [this folder](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ui/src/components/k8s-resources), you will need to add a new file called `CronJob.tsx` which will define a component similar to the Deployment one defined [here](https://github.com/cyclops-ui/cyclops/blob/822e6d305bc74a9b433e0f5b9cb0dd897564624a/cyclops-ui/src/components/k8s-resources/Deployment.tsx#L25).

Also, you will need to add your CronJob component to [this switch statement](https://github.com/cyclops-ui/cyclops/blob/822e6d305bc74a9b433e0f5b9cb0dd897564624a/cyclops-ui/src/components/pages/ModuleDetails.tsx#L375).

Reach out if you need any help

**Comment by samarsrivastav** [comment]
hey @petar-cvit , i have closed the 2nd pr and have updated the changes in #357 .
