### ISSUE TITLE
`cyctl` telemetry flag

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#364]
### Problem

When installing Cyclops with `kubectl` and the install manifests, you have the option to turn off telemetry. But when installing Cyclops with `cyctl` and the `init` command, this option does not exist. 

### Solution

Implement a `—-disable-telemetry` flag to disable telemetry when installing Cyclops via `cyctl`.

The command should look like the following:

```yaml
cyctl init —-disable-telemetry
```

**Comment by thebigbone** [comment]
How is telemetry disabled with `kubectl`?

**Comment by KaradzaJuraj** [comment]
You can find details in our documentation [here](https://cyclops-ui.com/docs/usage_metrics/).

You need to add the environment variable to cyclops-ctrl deployment

**Comment by thebigbone** [comment]
> You need to add the environment variable to cyclops-ctrl deployment. You can find details in our documentation [here](https://cyclops-ui.com/docs/usage_metrics/).

Got it. So, the most simple solution is to inject this environment variable while running `init`. I will try to implement it.

**Comment by KaradzaJuraj** [comment]
Yes! I'll assign you to the issue then 👍
