### ISSUE TITLE
Namespace in module header

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#365]
### Problem
When looking at the module overview screen from the developer's perspective, it is unclear what cyclops means underneath the name of the module.
![Screenshot 2024-06-23 at 15 02 21](https://github.com/cyclops-ui/cyclops/assets/101581637/3866f31e-1a55-48ad-9508-c9fc85dd09f8)

### Solution
Add `Namespace:` in front of the namespace name -> “**Namespace**: cyclops”

**Comment by tanbirali** [comment]
I will like to take this
