### ISSUE TITLE
Link to the template on Edit Module screen

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#366]
### Problem

The edit screen should have a link to the template origin, like the link in the Module overview header.

### Solution

Make the commit hash next to the `Load` button a link that points towards the origin of the template and make it clickable.
![Screenshot 2024-06-25 at 16 08 39](https://github.com/cyclops-ui/cyclops/assets/101581637/5f6021d1-4c74-4ede-9075-41e037a29250)

**Comment by tanbirali** [comment]
Would you please elaborate what do you mean by pointing to the origin of the template.

**Comment by KaradzaJuraj** [comment]
I'm sorry for the long wait.

Pointing to the origin of the template -> a link to where the template is stored

You can check [here](https://github.com/cyclops-ui/cyclops/blob/cd0fdfda46bab2f4fcebf41bea8079b7168e4ff5/cyclops-ui/src/components/pages/ModuleDetails.tsx#L654) how to find the origin of the template.

**Comment by tanbirali** [comment]
Do you want that hash to be replaced by a link or the hash will redirect and be clickable? If I go with the second approach it then I need to enable the input field which isn't required.
