### ISSUE TITLE
Button Emphasis

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#367]
### Problem

The following buttons should be more visible.

![Screenshot 2024-06-23 at 15 15 05](https://github.com/cyclops-ui/cyclops/assets/101581637/a2bf0464-8813-4e55-84e6-23eaf235a125)

![Screenshot 2024-06-23 at 15 15 14](https://github.com/cyclops-ui/cyclops/assets/101581637/e9a87fc6-e1e4-4c8a-9d8e-e5a3fec94e78)

### Solution

Change their type to primary, making them stand out with the orange color on similar buttons (like the button for adding new templates).

**Comment by Masum00x** [comment]
I would like to contribute,please assign me..

**Comment by petar-cvit** [comment]
Sure thing @Masum00x

**Comment by petar-cvit** [comment]
Hey @Masum00x, do you have any updates on the issue. If you have any questions, feel free to reach out

**Comment by Wasiim105** [comment]
@petar-cvit  I would like to take this issue.

**Comment by KaradzaJuraj** [comment]
Let's wait for @Masum00x for any new updates.
