### ISSUE TITLE
Too many status indicators on deployments

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#368]
### Problem

There are too many status indicators in the following image.
![Untitled](https://github.com/cyclops-ui/cyclops/assets/101581637/48b2b658-58c9-4488-b7f1-eb26cb63f009)
### Solution

1. The first ✅ represents the **status of the module** → this one needs to stay
2. The second ✅ represents the **status of the deployment** → this one needs to stay
3. The third ✅ also represents the **status of the deployment** → **this one we can remove**

**Comment by tanbirali** [comment]
I want to work on this, can you please assign me this
