### ISSUE TITLE
Disable download when no logs are present

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#369]
### Problem

When there are no logs available and we try to download them, we get an empty text file.
![Screenshot 2024-06-23 at 15 29 49](https://github.com/cyclops-ui/cyclops/assets/101581637/ddc66965-71e4-47fb-a2a5-86a8c56d72f8)

### Solution

Disable the `Download` button when no logs are available

**Comment by SrushtiAckno** [comment]
Can I try working on this?

**Comment by SrushtiHaryan** [comment]
Can I try working on this issue?

**Comment by petar-cvit** [comment]
Sure thing @SrushtiHaryan. Let us know if you will have any questions

**Comment by SrushtiHaryan** [comment]
![image](https://github.com/cyclops-ui/cyclops/assets/74239252/3a5e187e-30ae-4727-b426-486bf01bb975)
for now i have disabled the download button when the logs are empty

i want to test the case when the logs are non-empty, can you suggest on how do i trigger logs on the deployment that i made of nginx:

these are the deployments:

![image](https://github.com/cyclops-ui/cyclops/assets/74239252/3f44bbbe-3d8d-4ece-83a8-37a9a3bf9f32)

**Comment by petar-cvit** [comment]
Hey @SrushtiHaryan, do you have any updates on the issue. If you have any questions, feel free to reach out

**Comment by SrushtiHaryan** [comment]
> Hey @SrushtiHaryan, do you have any updates on the issue. If you have any questions, feel free to reach out

Hi, so i worked on it, i have disabled the button when no logs are available:
![image](https://github.com/cyclops-ui/cyclops/assets/74239252/b5aa89ea-68e6-4116-88bd-022b7e95c21a)
I am currently working on testing the functionality when logs are available by creating a new module and triggering logs. As I am relatively new to this process, I am still figuring it out.

**Comment by SrushtiHaryan** [comment]
Additionally, I wanted to confirm if Deployment.tsx is the only page where we need to fix this issue. The code base has multiple download log buttons, such as in DaemonSet.tsx, CronJob.tsx, etc. Should I apply the same fix to these files as well?

**Comment by petar-cvit** [comment]
> Additionally, I wanted to confirm if Deployment.tsx is the only page where we need to fix this issue. The code base has multiple download log buttons, such as in DaemonSet.tsx, CronJob.tsx, etc. Should I apply the same fix to these files as well?

We have recently extracted the whole pods table to a separate component we can reuse so you can update the logs modal in the PodTable component [here](https://github.com/SrushtiHaryan/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/common/PodTable.tsx). It will then be applied to all resources having pods
