### ISSUE TITLE
Logs formatting

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#370]
### Problem

When downloading logs, they are downloaded as a single string with no line breaks. This makes it unreadable.

### Solution

Implement line breaks in the downloaded text file. You can test it out by deploying `redis` with the `redis-demo` template and downloading logs from its pods.

**Comment by hanshal101** [comment]
I can work on this!!!

**Comment by KaradzaJuraj** [comment]
@hanshal101 go for it 👍
