### ISSUE TITLE
Default Service Port Name

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#371]
### Problem

It is legitimate for a service port to have no value in its name. We should implement a default so that it is not empty when deployed to Cyclops.
![Screenshot 2024-06-23 at 15 53 08](https://github.com/cyclops-ui/cyclops/assets/101581637/086847c5-5b4c-41f4-977b-60d6483c4d57)

### Solution

When a service port has no name, the default display should be `<not set>` You can test it out with the `redis-demo` template

**Comment by tanbirali** [comment]
I will like to work on this
