### ISSUE TITLE
State persists when deleting resources

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#372]
### Problem
When deleting multiple resources, the input state persists.

![Untitled](https://github.com/cyclops-ui/cyclops/assets/101581637/1dacd175-474c-4168-a464-1274e55b1177)

![Screenshot 2024-06-23 at 17 54 36](https://github.com/cyclops-ui/cyclops/assets/101581637/c36e35dc-16cd-4377-8e90-385d75d2a398)
### Solution
Clear the input state upon deletion of the resource.

**Comment by samarsrivastav** [comment]
could you tell the steps so that i can reach this issue.
also could you give a recording of the issue.

**Comment by KaradzaJuraj** [comment]
Of course!
1. You can deploy the [redis-demo template](https://github.com/cyclops-ui/templates/tree/main/redis) and **enable replication**.
2. Once deployed it's deployed, `Edit` the module and **turn off replication**
3. Now you will have a service and a deployment with warning signs 
![Screenshot 2024-07-05 at 12 46 15](https://github.com/cyclops-ui/cyclops/assets/101581637/93d06035-d618-4237-b048-db63f986250f)
4. Delete the unused Service
5. Then try to delete the deployment, and you will see the issue

Hope this helps @samarsrivastav !
