### ISSUE TITLE
`Edit` and `Delete` in templates header

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#373]
Add `Edit` and `Delete` descriptions in the header of the templates table.
![Screenshot 2024-06-23 at 14 50 31](https://github.com/cyclops-ui/cyclops/assets/101581637/79eb7b45-51f9-4e97-b8dd-bd0216b122b5)

**Comment by tanbirali** [comment]
I want to work on this

**Comment by petar-cvit** [comment]
Hey @tanbirali, sure thing!
