### ISSUE TITLE
Namespace filter in the Nodes tab

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#374]
### Problem
We want to be able to view resources deployed only in specific namespaces.

![Screenshot 2024-06-23 at 14 59 11 (1)](https://github.com/cyclops-ui/cyclops/assets/101581637/fd964c16-acca-4209-9e77-229bc00d78fe)

### Solution
Implement filters to display resources per namespace (all / default / cyclops …) similar to how `Name` has a filter.

**Comment by m2lusen** [comment]
Hi, I would be interested in contributing to this.

However, when I started to try and start a branch of the code I encountered the following error when trying to start cyclops-ui.

"warning ..\..\..\..\..\package.json: No license field
$ REACT_APP_CYCLOPS_CTRL_HOST=http://localhost:8888 node_modules/.bin/react-scripts start
'REACT_APP_CYCLOPS_CTRL_HOST' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."

Any help would be appreciated

**Comment by petar-cvit** [comment]
Hey @m2lusen, sure thing!

Are you working on windows? If so, can you update the [start script](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/package.json#L48) 
```
"start": "set REACT_APP_CYCLOPS_CTRL_HOST=http://localhost:8888 node_modules/.bin/react-scripts start",
```
to `package.json` and try `yarn start` again. I'll find a way for it to work out of the box.

**Comment by petar-cvit** [comment]
Alternatively, remove the env variable completely from package.json like below
```
"start": "node_modules/.bin/react-scripts start",
```
Set the env var in your cmd (`set REACT_APP_CYCLOPS_CTRL_HOST=http://localhost:8888`), and then run `yarn start` from the same cmd window

Let me know if it works

**Comment by m2lusen** [comment]
Great. Ive got it working now, I had to remove the env variable from package.json, it still wasn't working after updating the start script initially.

Thank you for the help
