### ISSUE TITLE
imagePullSecrets 

### ISSUE THREAD

**Issue by ranrsg** [cyclops-ui/cyclops#393]
**Describe the bug**
I am trying to deploy a simple helm chart with imagePullSecrets and getting the following error in cyclops-ctrl:
```
2024-07-03T10:20:35Z    ERROR   reconciler      could not apply resource        {"module namespaced name": "tst", "gvk": "apps/v1, Kind=Deployment", "resource namespaced name": "/*****", "error": "Deployment in version \"v1\" cannot be handled as a Deployment: json: cannot unmarshal array into Go struct field PodSpec.spec.template.spec.imagePullSecrets of type v1.LocalObjectReference"}
github.com/cyclops-ui/cyclops/cyclops-ctrl/internal/modulecontroller.(*ModuleReconciler).generateResources
        /build/internal/modulecontroller/module_controller.go:242
github.com/cyclops-ui/cyclops/cyclops-ctrl/internal/modulecontroller.(*ModuleReconciler).moduleToResources
        /build/internal/modulecontroller/module_controller.go:181
github.com/cyclops-ui/cyclops/cyclops-ctrl/internal/modulecontroller.(*ModuleReconciler).Reconcile
        /build/internal/modulecontroller/module_controller.go:142
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
```

I am using the auto generated Helm chart value - this is how the `imagePullSecrets` declered in there:
```
imagePullSecrets:
  - name: secret
```

This is how I set the `imagePullSecrets` property in the  values.schema.json:
```
"imagePullSecrets": {
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
      "name": {
          "type": "string"
      }
      },
      "required": [ "name" ]
  }
```
Tried also just setting the type to array, array of strings, and array if just object - same behevior for all.

*Helm lint and template works with no errors.

**Screenshots**
![image](https://github.com/cyclops-ui/cyclops/assets/125865943/1143b462-e4cf-4550-bebb-a3a566223329)

**Comment by petar-cvit** [comment]
Hey @ranrsg, thanks for reporting.

I tried creating a chart with `helm create` to reproduce it and it also failed. So instead of rendering
```
imagePullSecrets:
        - name: secret
```
Cyclops renders:
```
imagePullSecrets:
        - - name: secret
```
with two dashes, which fails when you try to apply it. The problem is likely caused by the `toYaml` helm function, but I will look into it further and let you know.

Sorry for the inconvenience. We will look into it. For the time being, I suggest replacing this part of the chart:
```
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
```
with a for loop that goes over all secrets and maps them to the yaml object.

**Comment by ranrsg** [comment]
Thanks @petar-cvit - I will check this out and wait for further updates.

Also, not sure if it is already supported, but will be nice to have the option to see this how Cyclops renders resources in case of an error (maybe a DEBUG mode).

**Comment by petar-cvit** [comment]
> Also, not sure if it is already supported, but will be nice to have the option to see this how Cyclops renders resources in case of an error (maybe a DEBUG mode).

Yup, was just thinking about it :)

**Comment by petar-cvit** [comment]
@ranrsg, we added a `view manifest` button to the module details page. Hope this will help with debugging

<img width="700" alt="Screenshot 2024-08-22 at 18 22 23" src="https://github.com/user-attachments/assets/50adb388-e804-4663-bf84-91f447e40078">
