### ISSUE TITLE
Default app template

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#40]
**Is your feature request related to a problem? Please describe.**
In some cases an instance of Cyclops will use only one template for applications (or at least in the majority of cases). There needs to be a way to set a default template for an instance of Cyclops that is loaded when a user tries to create a new module.

**Describe the solution you'd like**
Add an environment variable with a default template and load it automatically from the UI. Then, the user of Cyclops would set the environment variable in the configuration of the deployment and would have the template loaded automatically

**Comment by Anmol1696** [comment]
+1
This would be a really nice feature.
