### ISSUE TITLE
Pass module name when rendering rollback manifests

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#420]
**Is your feature request related to a problem? Please describe.**
When a user needs to perform a rollback of a Module, Cyclops renders a manifest of that particular module version. While doing that, the UI sends a request with all the module details so the manifest can be generated. The name of the module is never mapped when the endpoint is called, which results in an incomplete manifest. You can find the handler function for the manifest endpoint [here](https://github.com/cyclops-ui/cyclops/blob/d09d1dd29b7d3f609a3809a2437c82018d34d95f/cyclops-ctrl/internal/controller/modules.go#L139).

https://github.com/user-attachments/assets/8b44bfb9-f89d-4e3a-af6a-a8efcea5307b

In the video above I have used the `demo` template that comes baked in with Cyclops. I edited the module a couple of times, but when I go to a module > Rollback > Rollback, there is no name in the previous manifest. Adding the name on the backend will fix this issue.

**Describe the solution you'd like**
Map the module name, which can be fetched from the path parameters, to the module passed to the manifest renderer.

**Additional context**
To be able to see any history entry of the module, you will need to edit the module at least once after creation.

**Comment by priyanshuverma-dev** [comment]
I would like to work on this issue @petar-cvit.

**Comment by petar-cvit** [comment]
Sure @priyanshuverma-dev
