### ISSUE TITLE
Validating Multiple Templates Rotates Only The Last Icon

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#421]
In the templates tab, it is possible to start the validation process for multiple templates simultaneously, but the icon will change only for the last one you started.

We want the icon to be changed for every template that is currently being validated.

**Comment by nipunh** [comment]
@KaradzaJuraj Can you assign me this issue

**Comment by KaradzaJuraj** [comment]
Of course @nipunh!

**Comment by petar-cvit** [comment]
Hey @nipunh, do you have any updates on the issue? Let us know if you have any questions

**Comment by nipunh** [comment]
> Hey @nipunh, do you have any updates on the issue? Let us know if you have any questions

Hi, I have completed the local setup, and working on the task. will update soon
