### ISSUE TITLE
Node Gauges

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#422]
The gauges on the NodeDetails page are outdated and require an update.

<img width="1209" alt="Screenshot 2024-07-16 at 12 01 06" src="https://github.com/user-attachments/assets/78cb05b2-eca1-4149-a248-b9ba8a168fd5">

To style them in sync with the rest of the application, use the AntDesign library and the [progress components](https://ant.design/components/progress).

**Comment by ak708** [comment]
Hey @KaradzaJuraj, could i work on this one? Could you assign it to me?

**Comment by KaradzaJuraj** [comment]
Of course @ak708!

**Comment by petar-cvit** [comment]
Hey @ak708, we just merged a PR that solves this issue. I'm sorry for the miscommunication, but I didn't see somebody was already assigned here. Feel free to pick another issue

**Comment by ak708** [comment]
@petar-cvit No issues. Ill work on another one.
