### ISSUE TITLE
Implement template search

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#426]
**Is your feature request related to a problem? Please describe.**
The scope of the issue is to implement a search of templates by name [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/TemplateStore/TemplateStore.tsx).

**Describe the solution you'd like**
You can check out the pod search in [node details](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/NodeDetails.tsx) and implement it similarly.

**Comment by kom-senapati** [comment]
I would like to solve it

**Comment by petar-cvit** [comment]
sure thing @kom-senapati
