### ISSUE TITLE
Implement node search

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#427]
Is your feature request related to a problem? Please describe.
The scope of the issue is to implement a search of nodes by name [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/Nodes.tsx).

Describe the solution you'd like
You can check out the pod search in [node details](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/NodeDetails.tsx) and implement it similarly.

**Comment by ashish111333** [comment]
I want to work on this can you assign this to me.

**Comment by petar-cvit** [comment]
Sure thing @ashish111333. Let us know if you will have any questions

**Comment by ashish111333** [comment]
> Sure thing @ashish111333. Let us know if you will have any questions

sure. I WILL let you know if I need some help.
