### ISSUE TITLE
Implement Validate All Templates Button 

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#429]
In the Templates tab, each template has a `Validate` button. Once you have a lot of templates it is tedious to validate them one by one.

We should implement a `Validate all` button that will start the validation process for them all. Place the button in the lower right corner.

**Comment by sneha-4-22** [comment]
Hi @KaradzaJuraj Can i work on this ? please assign me.

**Comment by KaradzaJuraj** [comment]
Of course! I assigned you @sneha-4-22

**Comment by petar-cvit** [comment]
@sneha-4-22, do you have any updates on the issue?

**Comment by Wasiim105** [comment]
@petar-cvit can you assign me this issue ?

**Comment by petar-cvit** [comment]
Hey @Wasiim105, there is already a PR open by @ArnavK-09
