### ISSUE TITLE
NetworkPolicy Backend Implementation

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#433]
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment from default namespace called demo-app you would call:

```bash
/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default
```

The goal of the issue is to support NetworkPolicies on the same endpoint. The endpoint for fetching NetworkPolicies data would look like this: 

```bash
 /resources?group=apps&version=v1&kind=NetworkPolicy&name=&namespace=
```

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ctrl/internal/controller/modules.go), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ctrl/internal/cluster/k8sclient/client.go).

The endpoint should return data about its rules, you can find more about it [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#networkpolicy-v1-networking-k8s-io)

A structure similar to this one is preferred: 

```bash
 {”ingress”: [array_of_rules], ”egress”:[array_of_rules]}
```

Refer to this PR on adding new types https://github.com/cyclops-ui/cyclops/pull/259

**Comment by pithecuse527** [comment]
Hello,
May I take this?

**Comment by KaradzaJuraj** [comment]
Yes! Assigned you @pithecuse527

**Comment by ashish111333** [comment]
@pithecuse527  are you working on this ?

**Comment by pithecuse527** [comment]
@ashish111333 

Apologies for the delay. The update should be completed within this week.
