### ISSUE TITLE
ClusterRole Backend Implementation

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#436]
When fetching resources for a Module, some resources are supported to return details about a specific resource. For example, the endpoint for Deployments will return more information about pods and their statuses, and the endpoint for Services will return information about the ports.

If you want to fetch information about a Deployment from the default namespace called demo-app you would call:

```bash
/resources?group=apps&version=v1&kind=Deployment&name=demo-app&namespace=default
```

The goal of the issue is to support ClusterRole on the same endpoint. The endpoint for fetching ClusterRole data would look like this: 

```bash
 /resources?group=apps&version=v1&kind=ClusterRole&name=&namespace=
```

The handler function for the endpoint is [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ctrl/internal/controller/modules.go), and you will have to handle a new type [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ctrl/internal/cluster/k8sclient/client.go).

The endpoint should return data about its `name`, `rules`, `resources`, `verbs`… (you can find more about it [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#clusterrole-v1-rbac-authorization-k8s-io)

Refer to this PR on adding new types https://github.com/cyclops-ui/cyclops/pull/259

**Comment by jplourenco1** [comment]
I would like to work on this, already worked on another backend, this seems to be very similar

**Comment by petar-cvit** [comment]
Sure @jplourenco1!

**Comment by petar-cvit** [comment]
@jplourenco1, do you have any updates on the issue? Let us know if you have any questions

**Comment by nikonhub** [comment]
Hello,

Is this issue still in development? I'd be glad to work on it, if not.

**Comment by petar-cvit** [comment]
@nikonhub feel free to take it!
