### ISSUE TITLE
Add `template` flag to cyctl on module creation

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#439]
**Is your feature request related to a problem? Please describe.**
When creating a module using cyctl, you need to provide flags to define the repo, path, and version of the template.

The scope of the issue is to add a flag called template, which accepts a string. If provided, `cyctl` needs to fetch the template store custom resource with the name provided via the `template` flag. Once the template store is fetched, repo, path and version defined in the template store are used for the module creation the same way its done with the flags.

You can find how to fetch a template store custom resource [here](https://github.com/cyclops-ui/cyclops/blob/ceb523172ef0a8e9845ea19f34e63d1559f5e220/cyctl/internal/describe/template_store.go#L24).

The solution should not remove the repo, path and version flags, but just add a new one. Additionally, template flag cant be combined none of the flags for repo, path and version.

**Comment by shivamrazorpay** [comment]
@petar-cvit if we provide template flag & (repo, path & version) flag. Will the values from template over ride the values provided in the flag or we should have a validation that either template flag is there or the other (repo,path & version) flag ??

**Comment by petar-cvit** [comment]
Hey @shivamrazorpay, lets throw an error if the template flag is set along repo, path or version

**Comment by shivamrazorpay** [comment]
@petar-cvit I have created a PR, but I am new to the repo, so not sure how to locally run the CLI.
Can you give me some resources? or you can review my Code.
Thank You.

**Comment by petar-cvit** [comment]
You should set up a k8s cluster and then you should be able to create modules there. To create a cluster on your local machine, you can follow out [contributing docs](https://github.com/cyclops-ui/cyclops/blob/main/CONTRIBUTING.md#cluster-setup)

**Comment by petar-cvit** [comment]
implemented in #456
