### ISSUE TITLE
Fetch resources managed by a cyclops module

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#455]
**Is your feature request related to a problem? Please describe.**
The same way cyclops API is able to retrieve the resources managed by a single module, `cyctl` should be able to fetch all the resources and print them to the terminal.

**Describe the solution you'd like**
You will need to add a new command to `cyctl` to fetch resources.
```
cyctl resources <module name>
```

To implement it, you will need to instantiate the [k8s client](https://github.com/cyclops-ui/cyclops/blob/d09d1dd29b7d3f609a3809a2437c82018d34d95f/cyclops-ctrl/internal/cluster/k8sclient/client.go#L43) and fetch the resources by using it. You can use the k8s client [method](https://github.com/cyclops-ui/cyclops/blob/3572c7c6d2b4140866b6dff3df4b16a5fabfe97d/cyclops-ctrl/internal/cluster/k8sclient/modules.go#L56)

**Comment by nitintecg** [comment]
Hi @petar-cvit ,
I'm interested to contribute on this issue. 
Sorry im new to GO and currently in learning phase so just having one doubt that since k8sclient is present in internal package of cyclops-ctrl package so it will not allows us to import in cyctl package ?

**Comment by petar-cvit** [comment]
@nitintecg Oh yeah, you are right. I can see how we can go around this. My first thought is extracting into the pkg package, but I'll see if there is something else we can do.

Thanks for bringing this up

**Comment by nitintecg** [comment]
@petar-cvit I'm interested to work on this. Do you have any updates ?
Thanks

**Comment by petar-cvit** [comment]
Hey @nitintecg, thanks for the bump. We can create a pkg folder and extract the k8s client there from the internal folder. Then, you would be able to import it and use it in cyctl.

Tried to find some alternatives, but I don't see a downside to extracting stuff to the `pkg`.

Let me know if you would like to take this one with this approach

**Comment by petar-cvit** [comment]
Hey @Abiji-2020, just to clarify the first point - `pkg` should be in the `cyclops-ctrl` folder.

Let's give @nitintecg some more time since he expressed he wanted to solve it and spotted a problem. I can assign you in case there is no updates

**Comment by Abiji-2020** [comment]
Ok then let us wait and let me check other issues to solve

**Comment by nitintecg** [comment]
Thanks. i will give update here once its done

**Comment by petar-cvit** [comment]
Thanks @nitintecg

**Comment by nitintecg** [comment]
Hi @petar-cvit ,
Should i create separate commit for moving k8sclient to pkg package ? currently in local i have replaced cyclops-ctrl module with local path.

**Comment by petar-cvit** [comment]
@nitintecg yeah, you can replace it in a separate PR. In that case, you don't need to use the replace directive
