### ISSUE TITLE
Add restart button

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#464]
**Is your feature request related to a problem? Please describe.**
K8s resources like [Deployments](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/Deployment.tsx), [Statefulsets](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/StatefulSet.tsx) and [Daemonsets](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/DaemonSet.tsx) can be restarted and the scope of the issue is to implement a button that would call a restart endpoint for those resources.

Restart endpoint has already been implemented on the Cyclops backend as part of #342 (PR #406). When the button is cliked, it should call the following endpoint with the POST method: 
```
resources/restart?group=apps&version=v1&kind=<Deployment, StatefulSet or DaemonSet>&name=<name>&namespace=<namespace>
```

**Comment by RS-labhub** [comment]
Will take this up!

**Comment by petar-cvit** [comment]
Sure @RS-labhub

**Comment by RS-labhub** [comment]
Hii, I won't be able to do it due to my exams. If you want, you can unassign me this issue. I'll ping you back.

**Comment by s-vamshi** [comment]
@petar-cvit can I work on this issue?

**Comment by s-vamshi** [comment]
@petar-cvit can I work on this issue?

**Comment by s-vamshi** [comment]
hi @petar-cvit , if i am not wrong this is the api _/api/resources/restart?group=apps&version=v1&kind=${}&name=${}&namespace=${}_  with no post request body right?
