### ISSUE TITLE
Validate Template Error Message

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#465]
A small notification will pop up from the top when successfully validating a template.

But when the validation is unsuccessful, you will get a big notification that takes up a large portion of the screen. This is an older version of our error alerts, and this should also be refactored to be a notification that pops up from the top. To change this, update the `checkTemplateReference()` function in TemplateStore.tsx.

<div flex>
<img width="45%" alt="Screenshot 2024-07-23 at 16 40 07" src="https://github.com/user-attachments/assets/8365977f-b529-4c92-9e6c-9c59ecca2e35">
<img width="45%" alt="Screenshot 2024-07-23 at 16 39 56" src="https://github.com/user-attachments/assets/95a4a12b-c62b-4aed-9e27-abce9eb15108">
<div>

**Comment by duplixx** [comment]
hey @KaradzaJuraj can i work on this

**Comment by KaradzaJuraj** [comment]
Of course @duplixx!

**Comment by s-vamshi** [comment]
@duplixx can you I take up this issue in case you have not started working on this

**Comment by s-vamshi** [comment]
No problem!
@KaradzaJuraj @petar-cvit can you please assign this issue to me?

**Comment by Wasiim105** [comment]
@KaradzaJuraj  can you assign me this issue ?

**Comment by KaradzaJuraj** [comment]
@Wasiim105 you can work on this issue, since @s-vamshi is already assigned to issue  https://github.com/cyclops-ui/cyclops/issues/464
