### ISSUE TITLE
Create Cyclops Grafana dashboard

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#468]
**Is your feature request related to a problem? Please describe.**
Cyclops controller currently exposes prometheus metrics on port `8081` and path `/metrics`. The goal of the issue is to add a Grafana dashboard that would show currently available metrics. You are free to design the dashboard and add panels to it.

**Describe the solution you'd like**
The dashboard should be pushed to the repository as a JSON in the `grafana/dashboard.json`.

**Comment by rimvydascivilis** [comment]
I would like to take this one.

**Comment by petar-cvit** [comment]
Sure @rimvydascivilis

**Comment by petar-cvit** [comment]
@rimvydascivilis do you have any updates on the issue? Let us know if you have any questions

**Comment by rimvydascivilis** [comment]
@petar-cvit I successfully set up Grafana and will create the dashboard tomorrow.

**Comment by petar-cvit** [comment]
@rimvydascivilis thanks, let me know if we need to make changes to our deployments. By changes, I mean exposing another port, adding some Prometheus specific annotations, or something else.

Just note that you need to scrape metrics from the `cyclops-ctrl` only. `cyclops-ui` does not expose any metrics.

Solving this issue might require a lot of context of our setup so if there is anything we can help you with, feel free to post here.
