### ISSUE TITLE
Multiarchitecture image support

### ISSUE THREAD

**Issue by patelvp** [cyclops-ui/cyclops#489]
I was trying this out on a test cluster. My test cluster runs arm nodes. Quickly ran into issues since there is no published arm images. 
Is there any way to run this on clusters that have only arm nodes?
I could see this being a good addition as more and more users are moving to arm based workloads

**Comment by petar-cvit** [comment]
Hey @patelvp, we've made a multi platform build for a rc release. You can try installing it with
```
kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/build-multiarch-images/install/cyclops-install.yaml && kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/build-multiarch-images/install/demo-templates.yaml
```
Currently, we are building for `linux/amd64`, `linux/arm64`

**Comment by patelvp** [comment]
Thanks for the quick turnaround on this
