### ISSUE TITLE
It should be great to add dark mode in docs

### ISSUE THREAD

**Issue by priyanshuverma-dev** [cyclops-ui/cyclops#497]
**Is your feature request related to a problem? Please describe.**
We all are developers and we a all know that we love dark modes. So that, bugs and hide 🤣.

**Describe the solution you'd like**
It would be great to add dark mode in docs.

**Describe alternatives you've considered**
I think docs are built with docusaurus. it can be a easy change to do.

**Additional context**
N/A

**Comment by petar-cvit** [comment]
Hey @priyanshuverma-dev, I agree. Yes, we built our docs with docusaurus so you can check how to add the dark/light mode switch. Let me know if I can help you

**Comment by priyanshuverma-dev** [comment]
I am working on it. 
I removed social icons because they were not looking good there with theme switch.
And centre the text inside button have a look.
![image](https://github.com/user-attachments/assets/ce311be9-f328-4d3c-b4aa-3e849f32b147)

**Comment by priyanshuverma-dev** [comment]
Can we change background color? @petar-cvit

**Comment by petar-cvit** [comment]
Feel free to play around with color schemes and post it here. Honestly I like this blue background, but would love to see alternatives

**Comment by priyanshuverma-dev** [comment]
What about this dark mode:
![image](https://github.com/user-attachments/assets/621a0b44-ea70-4eb8-acc6-f86fa7e6aa25)

light mode:
![image](https://github.com/user-attachments/assets/13dafb8b-6677-47e9-9a3f-e726c290b769)

**Comment by priyanshuverma-dev** [comment]
little tweak to :
![image](https://github.com/user-attachments/assets/049fd19d-83ca-4d0f-954a-7ad15f7a25cd)

**Comment by priyanshuverma-dev** [comment]
@petar-cvit Change looks good to me. 
let me know from your side. So I can make a pull request.
Thanks
Priyanshu

**Comment by petar-cvit** [comment]
Sure, open a PR so its easier to discuss over the code
