### ISSUE TITLE
Dropdown menu to accept other then just enum fields

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#50]
**Is your feature request related to a problem? Please describe.**
In some cases, a dropdown is useful just as a suggestion, not as only options for the field

**Describe the solution you'd like**
Add a new field `suggestions` that behaves the same way as `enum`, but the UI will allow you to add any text you decide on

**Comment by s-vamshi** [comment]
@petar-cvit I would like to work on this issue

**Comment by s-vamshi** [comment]
@quest-bot embark

**Comment by petar-cvit** [comment]
Hey @s-vamshi, looks good from the functionality standpoint, but [this field uses `enum` to define possible options](https://github.com/cyclops-ui/templates/blob/e6d32bf4ada218c744ea19558d8e273d9bfe5bdd/app-template/values.schema.json#L84). `enum` is also used by Helm and if some other value is provided for that exact field, helm validation will fail.

You should also implement support for `x-suggestions` that will give the dropdown the effect you have shown in the video above. 

So if the schema is:
```json
"type": "string",
"enum": [
  "ClusterIP",
  "NodePort",
  "LoadBalancer"
],
```
behavior should stay the same as before, but if the scheme is
```json
"type": "string",
"x-suggestions": [
  "ClusterIP",
  "NodePort",
  "LoadBalancer"
],
```
then, the field should have the behavior you showed above.

**Comment by s-vamshi** [comment]
Hey @petar-cvit , I understand, if I am not wrong, I just need to add another field type with x-suggestions, when this comes up I need to show selectinputfield which allows custom options right?

**Comment by petar-cvit** [comment]
@s-vamshi, yup, sounds good
