### ISSUE TITLE
Loading Button Stuck After Canceling Modal with Empty File Reference in Add Module Page

### ISSUE THREAD

**Issue by s-vamshi** [cyclops-ui/cyclops#502]
**Describe the bug**
While creating a module, when I leave file reference field empty in load values from file will produce an error but the load button keeps on showing loading circle even after closing and reopening the load values from file modal

**To Reproduce**
1. Go to load values from file in add module page
2. Click on load button with file reference being empty
3. It displays an error message.
4. When I cancel the modal and reopen load values from file, the load button still shows loading circle until page is refreshed.

**Expected behavior**
Loading circle should be handled correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/8b0ec1ec-7569-4402-b6ba-0aa27975c197)

![image](https://github.com/user-attachments/assets/870969e2-8a28-42e5-9802-2c6f9a6df164)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Additional context**
can i work on this issue?

**Comment by petar-cvit** [comment]
Thanks for raising it @s-vamshi! Sure, will assign you to the issue
