### ISSUE TITLE
Disable save button before selecting a template

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#503]
**Is your feature request related to a problem? Please describe.**
When creating a new Module, you can choose templates from the dropdown. However, even before selecting the template, the Save button is active and can be clicked. The scope of the issue is to disable the button if no template is selected.

**Describe the solution you'd like**
You can check if the `template` state is set in the `NewModule` component. If not, the template is not selected, and the Save button should be disabled.

**Comment by Abito12** [comment]
Hi @petar-cvit, Please assign this issue to me
