### ISSUE TITLE
Add copy button to the `View Manifest` button

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#504]
**Is your feature request related to a problem? Please describe.**
Each resource deployed by a Module is represented in a separate collapse panel which has a `View Manifest` button. When the button is clicked, it opens a modal with the YAML config for a specific resource.

The scope of the issue is to add a button to the top right corner of the code editor with the manifest that will copy the manifest to the clipboard.

<img width="1284" alt="Screenshot 2024-08-11 at 23 00 40" src="https://github.com/user-attachments/assets/16800790-1acb-4480-8a36-c344035b13d3">

**Describe the solution you'd like**
Add a button to the the [manifest modal](https://github.com/cyclops-ui/cyclops/blob/84fb01da964b4c6e2a6c298d3809a19ad74ee03a/cyclops-ui/src/components/pages/ModuleDetails.tsx#L898).

**Comment by sarthakladhwe** [comment]
Hi, I'd love to take on this issue as my first contribution. I have experience with React and would be happy to help. Could you please assign this issue to me?

**Comment by petar-cvit** [comment]
Hey @sarthakladhwe, sure thing. Let us know if you have any questions
