### ISSUE TITLE
Add delete option to the pod table

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#513]
**Is your feature request related to a problem? Please describe.**
In the Cyclops UI, workload resources (Deployments, StatefulSets and DaemonSets) show a list of pods they are managing called [pod table](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/common/PodTable.tsx).

The scope of the task is to add a button to delete each one of the pods in the pod table. The button should be on the right side of the table row, for each pod. When the button is clicked, there should be a confirm modal to make sure pods are not deleted by accident. When a pod deletion is confirmed, you can call the delete endpoint on the Cyclops API. The resource deletion endpoint is also used [here](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/pages/ModuleDetails.tsx#L328), so you can check how to initiate a similar request.

**Comment by s-vamshi** [comment]
@petar-cvit can I work on this issue?

**Comment by Wasiim105** [comment]
@petar-cvit can you assign me this issue ?

**Comment by petar-cvit** [comment]
Hey, sorry but we refactored the UI part for pods and opened a new issue for it. Sorry for the confusion
