### ISSUE TITLE
Support multiple updates on `cyctl update module`

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#519]
**Is your feature request related to a problem? Please describe.**
`cycle update module` currently supports updating a single value in the module. The scope of the task is to support updating multiple values at once.

The command is currently invoked like below:
```
cyctl update module my-app --key="scaling.replicas" --value=3
```

After supporting updating multiple values, each updated value should be defined with a single flag that defines both key and value:
```
cyctl update module my-app --value="scaling.replicas=3" --value="expose.enabled=true" 
```

**Comment by rimvydascivilis** [comment]
I have completed one 'good first issue,' and I'm not sure if I can take on another. However, I would like to take a look at this one too.

**Comment by petar-cvit** [comment]
Sure, feel free to take it @rimvydascivilis
