### ISSUE TITLE
Implement watch mechanism for all resources

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#523]
**Is your feature request related to a problem? Please describe.**
As part of implementing streaming from the API to the UI, there needs to be a mechanism to listen to changes from the Kubernetes API.

The scope of the issue is to create a method on the [k8s client](https://github.com/cyclops-ui/cyclops/blob/90f2d765e14babd942940909efde73813033ab90/cyclops-ctrl/internal/cluster/k8sclient/client.go) that will accept and the group, version, kind, name and namespace and return a channel that publishes all events about that particular resource. Handling of the channel messages will be implemented in separate issues

**Comment by pravintargaryen** [comment]
Hi @petar-cvit please review https://github.com/cyclops-ui/cyclops/pull/525

**Comment by pravintargaryen** [comment]
@petar-cvit please check

**Comment by petar-cvit** [comment]
Will be implemented in #544
