### ISSUE TITLE
Implement view manifest pod action

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#539]
**Is your feature request related to a problem? Please describe.**

Similar to #538.

[PodTable](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/common/PodTable/PodTable.tsx) showing pods for Deployments, DaemonSets and StatefulSets has a column called actions with a menu. When expanded, the menu currently only has a button for checking pod logs.

<img width="1509" alt="Screenshot 2024-08-27 at 14 44 11" src="https://github.com/user-attachments/assets/ee7c4ba0-0805-446f-829f-6bee48026cf7">

The scope of the issue is to implement the `View Manifest` functionality and add a button to the same menu. When the button is clicked, a Modal showing the pods manifest needs to pop up.

You can fetch pod manifest from the `/manifest` backend endpoint.

You can check for a similar implementation of the `View Manifest` button in the [module details page](https://github.com/cyclops-ui/cyclops/blob/af65091e12c2a44867013a39a7919586599aa433/cyclops-ui/src/components/pages/ModuleDetails.tsx).

**Comment by knav33n** [comment]
Hello, could you kindly assign the issue to me?

**Comment by petar-cvit** [comment]
Hey @knav33n, sure

**Comment by knav33n** [comment]
@petar-cvit Should I include a copy button and add managed fields checkbox similar to those in the Deployment Manifest Modal?

**Comment by petar-cvit** [comment]
@knav33n yup, you can include that as well!

**Comment by knav33n** [comment]
@petar-cvit I've raised a pull request to address this issue.
