### ISSUE TITLE
Stream pod logs

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#555]
**Is your feature request related to a problem? Please describe.**
Currently, Cyclops UI supports fetching logs of a pod, but logs are not streamed in real time. The scope of the issue is to implement log streaming for pods on both the backend and frontend.

**Describe the solution you'd like**
You can use SSE to stream updates. https://github.com/cyclops-ui/cyclops/pull/544 implements streaming for resources so similar libs can be used.

**Comment by naineel1209** [comment]
hi @petar-cvit, I would like to pick this up, can you please assign it me?

**Comment by petar-cvit** [comment]
Sure! You can add a checkbox to the logs modal that would indicate that the logs need to be streamed

**Comment by naineel1209** [comment]
hi @petar-cvit,  had a doubt regarding this - 

Should I reuse the SSE implementation from #544 (wait for it to get merged) or work on the same branch as yours or start from scratch?

**Comment by petar-cvit** [comment]
Hey @naineel1209, you can create a branch from my branch and continue on my changes
