### ISSUE TITLE
`cyctl` reconcile module command

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#586]
**Is your feature request related to a problem? Please describe.**
Implement a `cyctl` subcommand to trigger module reconciliation. The subcommand does the same thing as the reconcile button on the module details page.

<img width="1150" alt="Screenshot 2024-09-23 at 15 57 18" src="https://github.com/user-attachments/assets/e1a57dd1-05b4-444b-911f-63b28078c36b">

The subcommand should look like:
```
cyctl reconcile <module name>
```

**Describe the solution you'd like**
You can trigger the reconciliation by fetching the module, adding the `cyclops/reconciled-at` with the current timestamp and updating the Module using a kubernetes client.

You can check the implementation of the same reconciliation triggering in `cyclops-ctrl` [here](https://github.com/cyclops-ui/cyclops/blob/cdc16dc449845c920b0e77dab6a8139c9b627cfe/cyclops-ctrl/internal/controller/modules.go#L350).

**Comment by Abiji-2020** [comment]
@petar-cvit I am interested to work on this Issue. 
I have to create  a command and get the module name and have to update with the annotation implemented similar to the reconciliation triggering in `cyclops-ctrl` ?

**Comment by petar-cvit** [comment]
@Abiji-2020 will assign you to the issue.

> I have to create a command and get the module name and have to update with the annotation implemented similar to the reconciliation triggering in cyclops-ctrl ?

Yeah, exactly
