### ISSUE TITLE
Emit Module reconciler metrics

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#598]
Module reconciler should emit Prometheus metrics about reconciliations it is processing. The reconciler should emit metrics about:
- number of reconciliations as a counter
- reconciliation duration as a histogram
- failed reconciliations as a counter

**Describe the solution you'd like**
The reconciler should accept a [Monitor](https://github.com/cyclops-ui/cyclops/blob/5760ffeff3a4deb3a818aa7a20f9141150e11878/cyclops-ctrl/internal/prometheus/handler.go#L12) in its constructor, which will need to implement new metrics and methods to accept new metrics.

**Comment by naineel1209** [comment]
@quest-bot embark
