### ISSUE TITLE
`cyctl get resources` missing namespace

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#599]
`cyctl` implements a `get resource <module name>` subcommand, which prints Kubernetes resources deployed from a Module.

The scope of the issue is to print the namespace of the deployed resources for a more clear overview of the resources.

**Comment by Abiji-2020** [comment]
I would like to work on this issue @petar-cvit

**Comment by Abiji-2020** [comment]
@quest-bot embark
