### ISSUE TITLE
support updating template stores using `cyctl`

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#600]
**Is your feature request related to a problem? Please describe.**
`cyctl` can currently create, list and delete template stores. It would be useful to update template stores using `cyctl` as well.

The command invocation should look like this:
```
cyctl update templates <templates-name> --path=<path> --repo=<repo> --version=<version> --icon=<icon>
```
`repo`, `path`, `version`, and `icon` are all optional, but at least one of them needs to be set. Flags update the following values in a template store object:

- repo - spec.repo
- path - spec.path
- version -  spec.version
- icon - [metadata.annotations.cyclops-ui.com/icon](http://metadata.annotations.cyclops-ui.com/icon)

When the subcommand is invoked, it should fetch the template store, update its values and update it in the cluster.

**Comment by Abiji-2020** [comment]
I would like to work on this PR @petar-cvit.

**Comment by Abiji-2020** [comment]
@quest-bot embark
