### ISSUE TITLE
`cyctl` interactive template creation

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#601]
Template stores can be created via the `cyctl` by using flags. For example:
```bash
cyctl create templates --repo=https://github.com/org/repo --path=my-template --version=main
```

The scope of the issue is to add the interactive mode when creating templates.

If none of the flags `repo`, `path`, or `version` are defined, a template can be created through the interactive mode. The user will be prompted to provide details about their template one by one.

You can look into integrating [promptui](https://github.com/manifoldco/promptui) or some other alternative for interactive CLI mode.

**Comment by Abiji-2020** [comment]
- I would like to work on this issue @petar-cvit 
- @quest-bot embark

**Comment by Abiji-2020** [comment]
@quest-bot embark
