### ISSUE TITLE
`cyctl` disable streaming flag

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#603]
**Is your feature request related to a problem? Please describe.**
When installing Cyclops with `kubectl` and the install manifests, you have the option to turn off streaming of updates to the UI. But when installing Cyclops with `cyctl` and the `init` command, this option does not exist. 

**Describe the solution you'd like**
Add a `--disable-streaming` flag to disable streaming resources when installing Cyclops via `cyctl`. If the flag is set, it should set the value of the `REACT_APP_ENABLE_STREAMING` environment variable in `cyclops-ui` deployment to `false`.

The command should look like the following:

```yaml
cyctl init --disable-streaming
```

**Comment by naineel1209** [comment]
Hi @petar-cvit,
I would like to work on this issue.

@quest-bot embark

**Comment by ArnavK-09** [comment]
@quest-bot embark

**Comment by petar-cvit** [comment]
@naineel1209 assigned you to the issue
