### ISSUE TITLE
`cyctl` interactive template auth rule creation

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#604]
The scope of the issue is to add the interactive mode when creating template auth rules.

If none of the flags repo, username, or password are provided, a template can be created through the interactive mode. The user will be prompted to provide details about their template auth rule one by one.

You can look into integrating [promptui](https://github.com/manifoldco/promptui) or some other alternative for interactive CLI mode.

**Comment by Abiji-2020** [comment]
@petar-cvit I would like to work on this issue and I have a doubt here, currently we are getting the username and password as values and directly validating it so I need to check beforehand that they are empty and use the values from the interactive else we need to go with the existing implications?

@quest-bot embark
