### ISSUE TITLE
Show TemplateResolvedVersion on `cyctl describe module`

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#605]
**Is your feature request related to a problem? Please describe.**
`cyctl` has a subcommand `describe` that allows you to check details about your deployed Cyclops Modules. The scope of this issue is to display `TemplateResolvedVersion` from the module state in the `cyctl describe module <module name>`.

**Comment by s-vamshi** [comment]
@quest-bot embark

**Comment by s-vamshi** [comment]
Hey @petar-cvit i would like to work on this issue.

**Comment by ArnavK-09** [comment]
@quest-bot embark

**Comment by petar-cvit** [comment]
@s-vamshi you can take this one since you reached out first

**Comment by s-vamshi** [comment]
Hey @petar-cvit thanks for assigning this to me!
