### ISSUE TITLE
Copy Module Name and Namespace buttons

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#639]
**Describe the solution you'd like**
Implement two buttons. The first should be placed next to the module name and the second to the module namespace (check out the orange Xs in the image below).

The first button copies the module's name to your clipboard, while the second copies the namespace. Use [AntDesign Icons](https://ant.design/components/icon)).

![Screenshot 2024-10-18 at 12 56 13](https://github.com/user-attachments/assets/bf6560c6-8241-4c8a-8c03-bb260b32ef0d)

**Comment by ArnavK-09** [comment]
Can I work on it?

**Comment by KaradzaJuraj** [comment]
hey @ArnavK-09, I'll assign you the issue and you can start working on it

**Comment by ArnavK-09** [comment]
@quest-bot embark
