### ISSUE TITLE
Emphasize delete modals

### ISSUE THREAD

**Issue by KaradzaJuraj** [cyclops-ui/cyclops#643]
When deleting modules and templates, a modal pops up that forces you to input the name of the resource you are deleting. We want to emphasize the name of the resource you are deleting more.

1. Update the module delete modal to have red text displaying the module's name in the title.
2. Update the template reference delete modal to have the name of the template reference in the title and color it red.

**Comment by ArnavK-09** [comment]
I'm willing to work on this, can I?

**Comment by Abiji-2020** [comment]
I would like to work on this. 
@quest-embark

**Comment by Abiji-2020** [comment]
I would like to work on this.
@quest-bot embark

**Comment by KaradzaJuraj** [comment]
hey @Abiji-2020 go for it, I'll assign you the issue. Thanks for picking this up

**Comment by Abiji-2020** [comment]
> hey @Abiji-2020, it seems that you have other issues assigned to you. Please finish those first, then take a new one

I have modified the works and completed on it, and pending was review  on it.

**Comment by Wasiim105** [comment]
@quest-bot embark
