### ISSUE TITLE
Add metrics to the controller

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#70]
**Is your feature request related to a problem? Please describe.**
We should add metrics to track the number of deployed modules, and changes the controller does on the cluster.

Decide which additional metrics should we expose.

**Describe the solution you'd like**
Expose metrics to prometheus

**Comment by hanshal101** [comment]
Hey @petar-cvit , Hanshal here. Well this issue looks interesting, can I work on this?
Also, Can you please give some more detail on this.

**Comment by petar-cvit** [comment]
Hey @hanshal101, of course, glad to have you here!

This issue was raised as a placeholder because we wanted to implement metrics tracking in the Cyclops controller at some point. I was thinking of implementing it using [Prometheus](https://prometheus.io/docs/guides/go-application/) since it's widely used.

The idea is that when somebody installs Cyclops into their cluster, they can monitor Cyclops behavior (e.g., the number of requests to the API, the number of modules, reconciliation events over time...), and their installation of Prometheus can scrape those metrics from the controller.

Later, I would create a dashboard our clients can import into their Grafanas, but that's another topic :)

Hope I managed to shed some light on the issue; let me know what you think

**Comment by petar-cvit** [comment]
Yup, that's exactly what I meant! You will need to initialize and monitor the metrics endpoint because we never started with the metrics efforts. The issue should be more focused on laying the foundation for metrics tracking, and then we can add other metrics as we go.

Just to sum up the scope of the issue:
- make sure we initialize prom monitor
- prometheus instances can scrape metrics from the controller
- emit one or two metrics to make sure the scraping works
  - other metrics will be added in separate issues/PRs
 
Does this make sense?
