### ISSUE TITLE
Docs dont detail how chart dependencies work or if they are supported

### ISSUE THREAD

**Issue by drdamour** [cyclops-ui/cyclops#71]
Maybe this is a roadmap item, but we r seeing https://helm.sh/docs/topics/charts/#chart-dependencies more often. Wondering ehat the current or planned support is

**Comment by petar-cvit** [comment]
Hey @drdamour, thanks for raising this! Cyclops currently does not support Helm chart dependencies, and we will add this to our documentation.

We should support it in future releases. We can open an issue, and you can add your input on that feature

**Comment by petar-cvit** [comment]
Hi @drdamour, we have added that chart dependencies are not yet implemented to our documentation [here](https://cyclops-ui.com/docs/templates/) and opened a new issue for implementing it https://github.com/cyclops-ui/cyclops/issues/75.

Feel free to add your input on the issue. We would be happy to discuss it!

**Comment by drdamour** [comment]
looks good thanks!
